' DGRMODE ?ENDSRC ( Avoid multiple loads )
" DGRLIB" LOADMOD"  "
" LINES" LOADMOD"  "
LOOKUP DGRPLOT    PLASMA DGRPLOT
LOOKUP DGRHLIN    PLASMA DGRHLIN
LOOKUP DGRVLIN    PLASMA DGRVLIN
LOOKUP DGRBLT     PLASMA DGRBLT
LOOKUP DGRTILE    PLASMA DGRTILE
LOOKUP DGRTILESTR PLASMA DGRTILESTR
LOOKUP DGRFILL    PLASMA DGRFILL
LOOKUP DGRVLB    PLASMA DGRVLB
LOOKUP DGRCLEAR   PLASMA DGRCLEAR
LOOKUP DGRMODE    PLASMA DGRMODE
LOOKUP DGRSHOW    PLASMA DGRSHOW
LOOKUP DGRSWAP    PLASMA DGRSWAP
LOOKUP DGRDRAWBUF PLASMA DGRDRAWBUF
LOOKUP DGRCOLOR   PLASMA DGRCOLOR
LOOKUP SETLINESPANS PLASMA SETLINESPANS
LOOKUP LINESPANS  PLASMA DGRLINE
LOOKUP DGRHLIN LOOKUP DGRVLIN SETLINESPANS