( LOADMOD" FILEIO"  FILEIO is already available in plforth )

LOOKUP FILEIO CONSTANT FILEIOAPI
FILEIOAPI  2  IFACE PLASMA GETFILEINFO
FILEIOAPI  3  IFACE PLASMA SETFILEINFO
FILEIOAPI  4  IFACE PLASMA GETEOF
FILEIOAPI  5  IFACE PLASMA SETEOF
FILEIOAPI  7  IFACE PLASMA OPEN
FILEIOAPI  8  IFACE PLASMA CLOSE
FILEIOAPI  9  IFACE PLASMA READ
FILEIOAPI 10  IFACE PLASMA WRITE
FILEIOAPI 11  IFACE PLASMA CREATE
FILEIOAPI 12  IFACE PLASMA DESTROY
FILEIOAPI 13  IFACE PLASMA RENAME
FILEIOAPI 14  IFACE PLASMA NEWLINE
FILEIOAPI 15  IFACE PLASMA ONLINE