' GRAFIX ?ENDSRC
" GRAFIX"  LOADMOD"  "
LOOKUP PENCOLOR   PLASMA GFXPENCOLOR
LOOKUP FILLCOLOR  PLASMA GFXFILLCOLOR
LOOKUP FILLSCREEN PLASMA GFXFILLSCREEN
LOOKUP PENMOVE    PLASMA GFXPENMOVE
LOOKUP PLOT       PLASMA GFXPLOT
LOOKUP LINE       PLASMA GFXLINE
LOOKUP LINETO     PLASMA GFXLINETO
LOOKUP RECT       PLASMA GFXRECT
LOOKUP FILLRECT   PLASMA GFXFILLRECT
LOOKUP BITBLT     PLASMA GFXBITBLT
LOOKUP DRAWMODE   PLASMA GFXDRAWMODE
LOOKUP SETMODE    PLASMA GFXSETMODE
