' GRAFIX ?ENDSRC
" GRAFIX"  LOADMOD"  "
LOOKUP PENCOLOR   PLASMA PENCOLOR
LOOKUP FILLCOLOR  PLASMA FILLCOLOR
LOOKUP FILLSCREEN PLASMA FILLSCREEN
LOOKUP PENMOVE    PLASMA PENMOVE
LOOKUP PLOT       PLASMA PLOT
LOOKUP LINE       PLASMA LINE
LOOKUP LINETO     PLASMA LINETO
LOOKUP RECT       PLASMA RECT
LOOKUP FILLRECT   PLASMA FILLRECT
LOOKUP BITBLT     PLASMA BITBLT
LOOKUP DRAWMODE   PLASMA DRAWMODE
LOOKUP SETMODE    PLASMA SETMODE
