' GRMODE ?ENDSRC ( Avoid multiple loads )
" GRLIB" LOADMOD"  "
" LINES" LOADMOD"  "
LOOKUP GRPLOT    PLASMA GRPLOT
LOOKUP GRHLIN    PLASMA GRHLIN
LOOKUP GRVLIN    PLASMA GRVLIN
LOOKUP GRBLT     PLASMA GRBLT
LOOKUP GRTILE    PLASMA GRTILE
LOOKUP GRTILESTR PLASMA GRTILESTR
LOOKUP GRFILL    PLASMA GRFILL
LOOKUP GRCLEAR   PLASMA GRCLEAR
LOOKUP GRMODE    PLASMA GRMODE
LOOKUP GRSHOW    PLASMA GRSHOW
LOOKUP GRSWAP    PLASMA GRSWAP
LOOKUP GRDRAWBUF PLASMA GRDRAWBUF
LOOKUP GRCOLOR   PLASMA GRCOLOR
LOOKUP SETLINESPANS PLASMA SETLINESPANS
LOOKUP LINESPANS    PLASMA GRLINE
LOOKUP GRHLIN LOOKUP GRVLIN SETLINESPANS
