SRC" PLASMA.4TH"
SRC" CONIO.4TH"
SRC" TURTLE.4TH"
" LINES" LOADMOD"  "
LOOKUP SETLINEPLOT PLASMA SETLINEPLOT
PFA PLOT SETLINEPLOT

: SHOW

  GR
  40 40 [ LOOKUP LINE ] LITERAL INITTURTLE
;

: SQUARE
    DUP MOVEFORWARD 90 TURNRIGHT
    DUP MOVEFORWARD 90 TURNRIGHT
    DUP MOVEFORWARD 90 TURNRIGHT
        MOVEFORWARD 90 TURNRIGHT
;

: SPIN
    361 0 DO
        I COLOR
        15 SQUARE
        I TURNTO
    10 +LOOP
;

SHOW SPIN
