SRC" plasma.4th"
SRC" conio.4th"
SRC" machid.4th"
LOOKUP CMDSYS 19 + @ PLASMA EXECSYS

: STRINPUT ( STR -- )
  DUP 1+ 255 ACCEPT SWAP C!
;
: STRING CREATE 256 ALLOT DOES> ; ( JUST ALLOCATE THE BIGGEST STRING POSSIBLE )

STRING DEST
STRING FILELIST

HOME
12 SPACES INVERSETEXT
." PLASMA HD INSTALL"
NORMALTEXT CR CR
." Enter destination " DEST STRINPUT
DEST C@ 0= ?ABORT" Destination required"
0 1 40 23 VIEWPORT

." Copying install files to " DEST (.") CR
FILELIST " -R * " STRCPY DEST STRCAT
" COPY" SWAP LOADMOD

DEST SETPFX DROP

FILELIST " HDINSTALL.4TH" STRCPY
" DEL" SWAP LOADMOD

FILELIST " HDINSTALL2.4TH HDINSTALL.4TH"  STRCPY
" REN" SWAP LOADMOD

." Stage 2..." CR
0 0 40 24 VIEWPORT

" PLASMA.SYSTEM" EXECSYS