' HGRMODE ?ENDSRC
" HGRLIB"  LOADMOD"  "
" LINES"   LOADMOD"  "
LOOKUP HGRPLOT    PLASMA HGRPLOT
LOOKUP HGRORPLOT  PLASMA HGRORPLOT
LOOKUP HGRXORPLOT PLASMA HGRXORPLOT
LOOKUP HGRHLIN    PLASMA HGRHLIN
LOOKUP HGRXORHLIN PLASMA HGRXORHLIN
LOOKUP HGRVLIN    PLASMA HGRVLIN
LOOKUP HGRXORVLIN PLASMA HGRXORVLIN
LOOKUP HGRBLT     PLASMA HGRBLT
LOOKUP HGRRECT    PLASMA HGRRECT
LOOKUP HGRXORRECT PLASMA HGRXORRECT
LOOKUP HGRCOPYSRC PLASMA HGRCOPYSRC
LOOKUP HGRANDSRC  PLASMA HGRANDSRC
LOOKUP HGRXORSRC  PLASMA HGRXORSRC
LOOKUP HGRORSRC   PLASMA HGRORSRC
LOOKUP HGRCOPYDST PLASMA HGRCOPYDST
LOOKUP HGRCLEAR   PLASMA HGRCLEAR
LOOKUP HGRMODE    PLASMA HGRMODE
LOOKUP HGRSHOW    PLASMA HGRSHOW
LOOKUP HGRSWAP    PLASMA HGRSWAP
LOOKUP HGRDRAWBUF PLASMA HGRDRAWBUF
LOOKUP HGRCOLOR   PLASMA HGRCOLOR
LOOKUP SETLINESPANS PLASMA SETLINESPANS
LOOKUP LINESPANS    PLASMA HGRLINE
LOOKUP HGRHLIN LOOKUP HGRVLIN SETLINESPANS
' TEXT 0= ?ENDSRC
: TEXT -1 HGRMODE DROP TEXT ;
