' TILEDRAW ?ENDSRC
" HGRTILE" LOADMOD"  " 
LOOKUP TILEDRAW     PLASMA TILEDRAW
LOOKUP TILEXORDRAW  PLASMA TILEXORDRAW
LOOKUP TILEORDRAW   PLASMA TILEORDRAW
LOOKUP TILEANDDRAW  PLASMA TILEANDDRAW
LOOKUP TILEDRAWSTR  PLASMA TILEDRAWSTR
LOOKUP TILEFROMTEXT PLASMA TILEFROMTEXT
LOOKUP TILEDRAWBUF  PLASMA TILEDRAWBUF