LOOKUP HRFORTH  ( HGR page 1 reserved )
NOT ?ABORT" Must run with HRFORTH."

SRC" PLASMA.4TH"
SRC" CONIO.4TH"
SRC" HGRLIB.4TH"
SRC" TURTLE.4TH"

: SHOW
  0 HGRMODE HGRDRAWBUF TILEDRAWBUF DROP
  280 192 INITTURTLE
  3 HGRCOLOR
;

: SQUARE
    DUP MOVEFORWARD 90 TURNRIGHT
    DUP MOVEFORWARD 90 TURNRIGHT
    DUP MOVEFORWARD 90 TURNRIGHT
        MOVEFORWARD 90 TURNRIGHT
;

: SPIN
    361 0 DO
        50 SQUARE
        I TURNTO
    10 +LOOP
;

: SPIN
    SHOW
    SPIN
;

SHOW SPIN