' MACHID ENDSRC
$01 CONSTANT MACHID.CLOCK
$02 CONSTANT MACHID.80COL
$30 CONSTANT MACHID.MEM
$20 CONSTANT MACHID.64K
$30 CONSTANT MACHID.128K
$C8 CONSTANT MACHID.MODEL
$00 CONSTANT MACHID.II
$40 CONSTANT MACHID.IIPLUS
$80 CONSTANT MACHID.IIE
$C0 CONSTANT MACHID.III
$88 CONSTANT MACHID.IIC
$08 CONSTANT MACHID.I
LOOKUP MACHID C@ CONSTANT MACHID
