' MACHID ENDSRC
$01 CONSTANT MACHID_CLOCK
$02 CONSTANT MACHID_80COL
$30 CONSTANT MACHID_MEM
$20 CONSTANT MACHID_64K
$30 CONSTANT MACHID_128K
$C8 CONSTANT MACHID_MODEL
$00 CONSTANT MACHID_II
$40 CONSTANT MACHID_IIPLUS
$80 CONSTANT MACHID_IIE
$C0 CONSTANT MACHID_III
$88 CONSTANT MACHID_IIC
$08 CONSTANT MACHID_I
LOOKUP MACHID C@ CONSTANT MACHID
