' IFACE ?ENDSRC
: IFACE 2 * + @ ;
LOOKUP CMDSYS 0  IFACE  CONSTANT PLASMAVER
LOOKUP CMDSYS 2  IFACE  CONSTANT CMDLINE
LOOKUP CMDSYS 3  IFACE  PLASMA   EXECMOD
LOOKUP STRCPY    PLASMA STRCPY
LOOKUP STRCAT    PLASMA STRCAT
LOOKUP TOUPPER   PLASMA TOUPPER
LOOKUP HEAPAVAIL PLASMA FREEMEM
: LOADMOD CMDLINE " . " STRCPY SWAP STRCAT DROP
  EXECMOD 0< ?ABORT" Failed to load module" ;
: LOADMOD" PAD SWAP STRCPY CHAR " WORD LOADMOD ;
: EDIT " ED" "  " LOADMOD ;
: EDIT" " ED" LOADMOD" ;
: CAT " CAT" "  " LOADMOD ;
: CAT" " CAT" LOADMOD" ;
: DEL" " DEL" LOADMOD" ;
: REN" " REN" LOADMOD" ;
: COPY" " COPY" LOADMOD" ;
: NEWDIR" " NEWDIR" LOADMOD" ;
LOOKUP FILEIO 0 IFACE PLASMA GETPFX
LOOKUP FILEIO 1 IFACE PLASMA SETPFX
: PFX. HERE GETPFX DROP HERE (.") ;
: PFX" 34 WORD SETPFX DROP ;
: PFA 32 WORD FIND 0= ?ABORT" Not found." DUP C@ + 8 + ;
