' PORTIO ?ENDSRC
" PORTIO" LOADMOD"  "

LOOKUP DIGITALREAD  PLASMA DIGITALREAD
LOOKUP PORTREAD     PLASMA PORTREAD
LOOKUP DIGITALWRITE PLASMA DIGITALWRITE
LOOKUP PORTWRITE    PLASMA PORTWRITE
LOOKUP ANALOGREAD   PLASMA ANALOGREAD
LOOKUP DELAY        PLASMA DELAY
LOOKUP STROBE       PLASMA STROBE
