' INITTURTLE ?ENDSRC
" INT32"  LOADMOD"  "
" SINCOS" LOADMOD"  "
" TURTLE" LOADMOD"  "
LOOKUP INITTURTLE    PLASMA INITTURTLE
LOOKUP CLIPLINE      PLASMA CLIPLINE
LOOKUP CLIPRECT      PLASMA CLIPRECT
LOOKUP TURNTO        PLASMA TURNTO
LOOKUP TURN          PLASMA TURN
LOOKUP MOVETO        PLASMA MOVETO
LOOKUP MOVE          PLASMA MOVE
LOOKUP MOVEP4        PLASMA MOVEP4
LOOKUP PENUP         PLASMA PENUP
LOOKUP PENDOWN       PLASMA PENDOWN
