' INITTURTLE ?ENDSRC
" INT32"  LOADMOD"  "
" SINCOS" LOADMOD"  "
" LINES"  LOADMOD"  "
" TURTLE" LOADMOD"  "
LOOKUP INITTURTLE    PLASMA INITTURTLE
LOOKUP CLIPLINE      PLASMA CLIPLINE
LOOKUP CLIPRECT      PLASMA CLIPRECT
LOOKUP FILLRECT      PLASMA FILLRECT
LOOKUP TURNTO        PLASMA TURNTO
LOOKUP TURNLEFT      PLASMA TURNLEFT
LOOKUP TURNRIGHT     PLASMA TURNRIGHT
LOOKUP MOVETO        PLASMA MOVETO
LOOKUP MOVEFORWARD   PLASMA MOVEFORWARD
LOOKUP MOVEBACKWARD  PLASMA MOVEBACKWARD
LOOKUP PENUP         PLASMA PENUP
LOOKUP PENDOWN       PLASMA PENDOWN
