' INITTURTLE ?ENDSRC
" TURTLE"  LOADMOD"  "
LOOKUP INITTURTLE    PLASMA INITTURTLE
LOOKUP CLIPRECT      PLASMA CLIPRECT
LOOKUP TURNLEFT      PLASMA TURNLEFT
LOOKUP TURNRIGHT     PLASMA TURNRIGHT
LOOKUP TURNTO        PLASMA TURNTO
LOOKUP MOVEFORWARD   PLASMA MOVEFORWARD
LOOKUP MOVETO        PLASMA MOVETO
LOOKUP PENUP         PLASMA PENUP
LOOKUP PENDOWN       PLASMA PENDOWN
