: ?PLASMA
    " IFACE" FIND
    0= IF
      " PLASMA.4TH" SRC
    THEN
;

?PLASMA ( Load PLASMA if not already )

 5 VARIABLE BALLCLR
10 VARIABLE BALLX
20 VARIABLE BALLY
10 VARIABLE OLDX
20 VARIABLE OLDY
1  VARIABLE INCX
1  VARIABLE INCY

: MOVEBALL
  BALLX @ 0=   IF INCX @ NEG INCX ! THEN
  BALLX @ 39 = IF INCX @ NEG INCX ! THEN
  BALLY @ 0=   IF INCY @ NEG INCY ! THEN
  BALLY @ 47 = IF INCY @ NEG INCY ! THEN
  INCX @ BALLX +!
  INCY @ BALLY +!
  BALLCLR @ GRCOLOR DROP
  BALLX @ BALLY @ GRPLOT DROP
  0 GRCOLOR DROP
  OLDX @ OLDY @ GRPLOT DROP
  BALLX @ OLDX !
  BALLY @ OLDY !
;

: BOUNCE
  0 GRMODE DROP
  BEGIN
    MOVEBALL
    ?TERMINAL
  UNTIL
  KEY
  40 TEXTMODE DROP
;

BOUNCE
