: IFACE 2 * + @ ;

LOOKUP CMDSYS 3 IFACE PLASMA   EXECMOD
LOOKUP CMDSYS 2 IFACE CONSTANT CMDLINE
LOOKUP STRCPY PLASMA STRCPY
LOOKUP STRCAT PLASMA STRCAT

: EDIT"
    CMDLINE " ED "  STRCPY
    CMDLINE 34 WORD STRCAT
    " ED" EXECMOD
;
