: IFACE 2 * + @ ;

LOOKUP CMDSYS 3 IFACE PLASMA   EXECMOD
LOOKUP CMDSYS 2 IFACE CONSTANT CMDLINE
LOOKUP STRCPY PLASMA STRCPY
LOOKUP STRCAT PLASMA STRCAT

: CPYCMD
    CMDLINE " . "  STRCPY DROP ( Need a dummy value for the module name )
    34 WORD CMDLINE SWAP STRCAT DROP ( Quote deliminted string )
;

: CMDEXEC
    CPYCMD
    EXECMOD 0< IF ." Failed to exec module" CR THEN
;

: LOADMOD"
    34 WORD ( Quote deliminted string )
    EXECMOD 0< IF ." Failed to load module" CR THEN
;

: EDIT"
    CPYCMD
    " ED" EXECMOD 0< IF ." Failed to run ED" CR ABORT THEN
;

( LOADMOD" FILEIO"  FILEIO is already available in plforth )

LOOKUP FILEIO CONSTANT FILEIOAPI
FILEIOAPI 0  IFACE PLASMA GETPFX
FILEIOAPI 1  IFACE PLASMA SETPFX

( LOADMOD" CONIO"  CONIO is already available in plforth )

LOOKUP CONIO CONSTANT CONIOAPI
CONIOAPI 3  IFACE PLASMA HOME
CONIOAPI 4  IFACE PLASMA GOTOXY
CONIOAPI 7  IFACE PLASMA TEXTMODE
CONIOAPI 8  IFACE PLASMA GRMODE
CONIOAPI 9  IFACE PLASMA GRCOLOR
CONIOAPI 10 IFACE PLASMA GRPLOT
CONIOAPI 11 IFACE PLASMA TONE
CONIOAPI 12 IFACE PLASMA RAND

