;
; EXTENDED REL MODULE WITH DEPENDENCIES, BYTECODE SEGMENT, AND INIT
;
 REL
 ORG $1000
;
; USEFUL ZERO PAGE LOCATIONS
;
SRC EQU $06
SRCL EQU SRC
SRCH EQU SRC+1
DST EQU SRC+2
DSTL EQU DST
DSTH EQU DST+1
TMP EQU $E7
TMPL EQU TMP
TMPH EQU TMP+1
ESTKH EQU $C0
ESTKL EQU $D0
DROPOP EQU $EF
NEXTOP EQU $F0
FETCHOP EQU NEXTOP+1
;
; JUMP TO BYTECODE INTERPRETER ADDRESS
;
INTERP EQU $03D0
;
; EXTERNALS USED BY THIS MODULE
;
 EXTRN PUTS
 EXTRN PUTLN
;
; EXT HEADER
;
 DW $6502
 DW 0        ; SYSFLAGS
 DW DEFSEG   ; DEF OFFSET
 DW 1        ; DEF COUNT (INCLUDING INIT)
 DW MODINIT  ; MOD INIT
 MSB ON
 ASC "CMDSY" ; MOD DEPENDENCIES (DCI BACKWARDS HI/LO BIT FROM REL FILE)
 MSB OFF
 ASC "S"
 DB 0
;
; DATA AND 6502 CODE SEGMENT
;
HIMSG STR "Hello"
HELLO DEF HELLO ; CALLABLE FROM EXTERNAL MODULES
 LDA #>HIMSG
 LDY #<HIMSG
 DEX
 STA ESTKL,X
 STY ESTKH,X
 JSR PUTS
 JMP PUTLN
BYEMSG STR "Goodbye"
GOODBYE DEF GOODBYE ; CALLABLE FROM EXTERNAL MODULES
 LDA #>BYEMSG
 LDY #<BYEMSG
 DEX
 STA ESTKL,X
 STY ESTKH,X
 JSR PUTS
 JMP PUTLN
;
; INITIALIZE MODULE AND RETURN SUCCESS
;
INIT LDA #$00
 JSR HELLO
 LDY #$00
 DEX
 STA ESTKL,X
 STY ESTKH,X
 RTS
;
; BYTECODE DEFS SEGMENT
;
 DB 0          ; PAD BYE
DEFSEG EQU *
;
; INIT CODE RUNS WHEN MODULE LOADED
;
MODINIT DB $54 ; CALL ASM INIT
 DW INIT
 DB $5C        ; RET
