(DEFINE
  (PLOTFUNC (LAMBDA (FN)
    (PROG (X Y)
      (SETQ X 0)
    A (SETQ Y (* 0.99 (FN (/ (- X 20) 20.0))))
      (IF (AND (> Y -1.0) (< Y 1.0))
        (PLOT X, (* (+ Y 1.0) 19.0)))
      (SETQ X (+ X 1))
      (IF (< X 40) (GO A))
      (RETURN 0)
    )
  ))
  (PLOTSIN (LAMBDA ()
    (PLOTFUNC '(LAMBDA (S) (SIN (* S PI))))
  ))
  (PLOTCOS (LAMBDA ()
    (PLOTFUNC '(LAMBDA (S) (COS (* S PI))))
  ))
)
(GR T)
(COLOR 2)
(PLOTSIN)
(COLOR 9)
(PLOTCOS)
