(define
  (lengthc (lambda (l)
    (prog (u v)
      (setq v 0)
      (setq u l)
    a (cond ((null u),(return v)))
      (setq v (+ 1 v))
      (setq u (cdr u))
      (go a)
     )
  ))
  (lengthi (lambda (l)
    (prog (u v)
      (setq v 0)
      (setq u l)
    a (if (null u) (return v) (setq v (+ 1 v)))
      (setq u (cdr u))
      (go a)
     )
   ))
)
