#!/bin/bash
PO_IMAGE=PLFORTH.po
cp ../sysfiles/BLANK140.po $PO_IMAGE
java -jar ac.jar -n $PO_IMAGE PLEIADES.4TH
cat ../sysfiles/PRODOS#FF0000 | java -jar ac.jar -p $PO_IMAGE PRODOS SYS
cat rel/apple/CMD#061000 | java -jar ac.jar -p $PO_IMAGE CMD BIN $1000
cat rel/apple/PLASMA.SYSTEM#FF2000 | java -jar ac.jar -p $PO_IMAGE PLASMA.SYSTEM SYS
cat rel/apple/FILEIO#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/FILEIO REL
cat rel/apple/CONIO#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/CONIO REL
cat rel/apple/VBLANK#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/VBLANK REL
cat rel/ARGS#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/ARGS REL
cat rel/LONGJMP#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/LONGJMP REL
cat rel/apple/INITSLOT#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/INITSLOT REL
cat rel/HRFORTH#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/HRFORTH REL
#cat rel/HR2FORTH#FE1000            | java -jar ac.jar -p   $PO_IMAGE sys/HR2FORTH REL
cat rel/TX2FORTH#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/TX2FORTH REL
cat rel/PLFORTH#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/PLFORTH REL
#cat rel/apple/COPY#FE1000          | java -jar ac.jar -p   $PO_IMAGE sys/COPY REL
#cat rel/apple/DEL#FE1000           | java -jar ac.jar -p   $PO_IMAGE sys/DEL REL
#cat rel/apple/REN#FE1000           | java -jar ac.jar -p   $PO_IMAGE sys/REN REL
#cat rel/apple/CAT#FE1000           | java -jar ac.jar -p   $PO_IMAGE sys/CAT REL
#cat rel/apple/TYPE#FE1000          | java -jar ac.jar -p   $PO_IMAGE sys/TYPE REL
#cat rel/apple/NEWDIR#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/NEWDIR REL
#cat rel/apple/MATCHFILES#FE1000    | java -jar ac.jar -p   $PO_IMAGE sys/MATCHFILES REL
cat rel/INT32#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/INT32 REL
cat rel/apple/PORTIO#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/PORTIO REL
#cat rel/FPSTR#FE1000               | java -jar ac.jar -p   $PO_IMAGE sys/FPSTR REL
#cat rel/FPU#FE1000                 | java -jar ac.jar -p   $PO_IMAGE sys/FPU REL
#cat rel/SANE#FE1000                | java -jar ac.jar -p   $PO_IMAGE sys/SANE REL
#cat ../sysfiles/FP6502.CODE#060000 | java -jar ac.jar -p   $PO_IMAGE sys/FP6502.CODE BIN
#cat ../sysfiles/ELEMS.CODE#060000  | java -jar ac.jar -p   $PO_IMAGE sys/ELEMS.CODE BIN
cat rel/ED#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/ED REL
cat rel/LINES#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/LINES REL
cat rel/SINCOS#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/SINCOS REL
cat rel/TURTLE#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/TURTLE REL
cat rel/apple/HGRFONT#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/HGRFONT REL
cat rel/apple/HGRTILE#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/HGRTILE REL
cat rel/apple/HGRLIB#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/HGRLIB REL
cat rel/apple/GRLIB#FE1000 | java -jar ac.jar -p $PO_IMAGE sys/GRLIB REL
#cat rel/apple/DGRLIB#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/DGRLIB REL
cat scripts/plasma.4th | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/PLASMA.4TH TXT
cat scripts/machid.4th | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/MACHID.4TH TXT
cat scripts/conio.4th | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/CONIO.4TH TXT
cat scripts/fileio.4th | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/FILEIO.4TH TXT
cat scripts/grlib.4th | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/GRLIB.4TH TXT
#cat scripts/dgrlib.4th             | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/DGRLIB.4TH TXT
cat scripts/hgrlib.4th | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/HGRLIB.4TH TXT
cat scripts/hgrfont.4th | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/HGRFONT.4TH TXT
cat scripts/int32.4th | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/INT32.4TH TXT
cat scripts/portio.4th | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/PORTIO.4TH TXT
cat scripts/turtle.4th | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/TURTLE.4TH TXT
#cat scripts/fpu.4th                | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/FPU.4TH TXT
cat scripts/rod.4th | java -jar ac.jar -ptx $PO_IMAGE scripts/ROD.4TH TXT
cat scripts/bounce.4th | java -jar ac.jar -ptx $PO_IMAGE scripts/BOUNCE.4TH TXT
#cat scripts/dbounce.4th            | java -jar ac.jar -ptx $PO_IMAGE scripts/DBOUNCE.4TH TXT
#cat scripts/hrbounce.4th | java -jar ac.jar -ptx $PO_IMAGE scripts/HRBOUNCE.4TH TXT
cat scripts/grturtle.4th | java -jar ac.jar -ptx $PO_IMAGE scripts/GRTURTLE.4TH TXT
cat scripts/hrturtle.4th | java -jar ac.jar -ptx $PO_IMAGE scripts/HRTURTLE.4TH TXT
cat scripts/hny26.4th | java -jar ac.jar -ptx $PO_IMAGE scripts/HNY26.4TH TXT
#cat scripts/hrplot.4th            | java -jar ac.jar -ptx $PO_IMAGE scripts/HRPLOT.4TH TXT
echo "+HRFORTH SCRIPTS/HRTURTLE.4TH" | java -jar ac.jar -ptx $PO_IMAGE AUTORUN TXT
