#!/bin/bash
./mkrel
cp ../sysfiles/BLANK800.po PLASMA-2.1.po
./ac.jar -n PLASMA-2.1.po PLASMA2
cat ../sysfiles/PRODOS#FF0000      | ./ac.jar -p   PLASMA-2.1.po PRODOS SYS
cat rel/apple/CMD#061000           | ./ac.jar -p   PLASMA-2.1.po CMD BIN $1000
cat rel/apple/CMD128#061000        | ./ac.jar -p   PLASMA-2.1.po CMD128 BIN $1000
cat rel/apple/PLASMA.SYSTEM#FF2000 | ./ac.jar -p   PLASMA-2.1.po PLASMA.SYSTEM SYS
cat rel/apple/PLVM.128#FF2000      | ./ac.jar -p   PLASMA-2.1.po PLVM.128 SYS
cat rel/apple/PLVM16#FF2000        | ./ac.jar -p   PLASMA-2.1.po PLVM16 SYS
cat ../doc/Editor.md               | ./ac.jar -ptx PLASMA-2.1.po EDITOR.README TXT

#mkdir sys
cat rel/apple/FILEIO#FE1000        | ./ac.jar -p   PLASMA-2.1.po sys/FILEIO REL
cat rel/apple/CONIO#FE1000         | ./ac.jar -p   PLASMA-2.1.po sys/CONIO REL
cat rel/LINES#FE1000               | ./ac.jar -p   PLASMA-2.1.po sys/LINES REL
cat rel/apple/HGRFONT#FE1000       | ./ac.jar -p   PLASMA-2.1.po sys/HGRFONT REL
cat rel/apple/HGRTILE#FE1000       | ./ac.jar -p   PLASMA-2.1.po sys/HGRTILE REL
cat rel/apple/HGRSPRITE#FE1000     | ./ac.jar -p   PLASMA-2.1.po sys/HGRSPRITE REL
cat rel/apple/HGRLIB#FE1000        | ./ac.jar -p   PLASMA-2.1.po sys/HGRLIB REL
cat rel/apple/GRLIB#FE1000         | ./ac.jar -p   PLASMA-2.1.po sys/GRLIB REL
cat rel/apple/DGRLIB#FE1000        | ./ac.jar -p   PLASMA-2.1.po sys/DGRLIB REL
cat rel/apple/COPY#FE1000          | ./ac.jar -p   PLASMA-2.1.po sys/COPY REL
cat rel/apple/DEL#FE1000           | ./ac.jar -p   PLASMA-2.1.po sys/DEL REL
cat rel/apple/REN#FE1000           | ./ac.jar -p   PLASMA-2.1.po sys/REN REL
cat rel/apple/CAT#FE1000           | ./ac.jar -p   PLASMA-2.1.po sys/CAT REL
cat rel/apple/NEWDIR#FE1000        | ./ac.jar -p   PLASMA-2.1.po sys/NEWDIR REL
cat rel/apple/TYPE#FE1000          | ./ac.jar -p   PLASMA-2.1.po sys/TYPE REL
cat rel/apple/MATCHFILES#FE1000    | ./ac.jar -p   PLASMA-2.1.po sys/MATCHFILES REL
cat rel/ARGS#FE1000                | ./ac.jar -p   PLASMA-2.1.po sys/ARGS REL
cat rel/ED#FE1000                  | ./ac.jar -p   PLASMA-2.1.po sys/ED REL
cat rel/FIBER#FE1000               | ./ac.jar -p   PLASMA-2.1.po sys/FIBER REL
cat rel/LONGJMP#FE1000             | ./ac.jar -p   PLASMA-2.1.po sys/LONGJMP REL
cat rel/MEMMGR#FE1000              | ./ac.jar -p   PLASMA-2.1.po sys/MEMMGR REL
cat rel/INET#FE1000                | ./ac.jar -p   PLASMA-2.1.po sys/INET REL
cat rel/DHCP#FE1000                | ./ac.jar -p   PLASMA-2.1.po sys/DHCP REL
cat rel/ETHERIP#FE1000             | ./ac.jar -p   PLASMA-2.1.po sys/ETHERIP REL
cat rel/apple/MOUSE#FE1000         | ./ac.jar -p   PLASMA-2.1.po sys/MOUSE REL
cat rel/apple/UTHERNET2#FE1000     | ./ac.jar -p   PLASMA-2.1.po sys/UTHERNET2 REL
cat rel/apple/UTHERNET#FE1000      | ./ac.jar -p   PLASMA-2.1.po sys/UTHERNET REL
cat rel/apple/PORTIO#FE1000        | ./ac.jar -p   PLASMA-2.1.po sys/PORTIO REL
cat rel/apple/JOYBUZZ#FE1000       | ./ac.jar -p   PLASMA-2.1.po sys/JOYBUZZ REL
cat rel/apple/SNDSEQ#FE1000        | ./ac.jar -p   PLASMA-2.1.po sys/SNDSEQ REL
cat rel/apple/JIT#FE1000           | ./ac.jar -p   PLASMA-2.1.po sys/JIT REL
cat rel/apple/JIT16#FE1000         | ./ac.jar -p   PLASMA-2.1.po sys/JIT16 REL
cat rel/apple/JITUNE#FE1000        | ./ac.jar -p   PLASMA-2.1.po sys/JITUNE REL
cat rel/apple/ZIPCHIP#FE1000       | ./ac.jar -p   PLASMA-2.1.po sys/ZIPCHIP REL
cat rel/LZ4#FE1000                 | ./ac.jar -p   PLASMA-2.1.po sys/LZ4 REL
cat rel/TFTPD#FE1000               | ./ac.jar -p   PLASMA-2.1.po sys/TFTPD REL
cat rel/INT32#FE1000               | ./ac.jar -p   PLASMA-2.1.po sys/INT32 REL
cat rel/FPSTR#FE1000               | ./ac.jar -p   PLASMA-2.1.po sys/FPSTR REL
cat rel/FPU#FE1000                 | ./ac.jar -p   PLASMA-2.1.po sys/FPU REL
cat rel/SANE#FE1000                | ./ac.jar -p   PLASMA-2.1.po sys/SANE REL
cat ../sysfiles/FP6502.CODE#060000 | ./ac.jar -p   PLASMA-2.1.po sys/FP6502.CODE BIN
cat ../sysfiles/ELEMS.CODE#060000  | ./ac.jar -p   PLASMA-2.1.po sys/ELEMS.CODE BIN
cat rel/apple/SOS#FE1000           | ./ac.jar -p   PLASMA-2.1.po sys/SOS REL
cat rel/apple/GRAFIX#FE1000        | ./ac.jar -p   PLASMA-2.1.po sys/GRAFIX REL
cat rel/HRFORTH#FE1000             | ./ac.jar -p   PLASMA-2.1.po sys/HRFORTH REL
cat rel/HR2FORTH#FE1000            | ./ac.jar -p   PLASMA-2.1.po sys/HR2FORTH REL
cat rel/PLFORTH#FE1000             | ./ac.jar -p   PLASMA-2.1.po sys/PLFORTH REL

#mkdir sys/scripts
cat scripts/hdinstall.4th     | ./ac.jar -ptx PLASMA-2.1.po HDINSTALL.4TH TXT
cat scripts/plasma.4th    	  | ./ac.jar -ptx PLASMA-2.1.po sys/scripts/PLASMA.4TH TXT
cat scripts/machid.4th    	  | ./ac.jar -ptx PLASMA-2.1.po sys/scripts/MACHID.4TH TXT
cat scripts/conio.4th     	  | ./ac.jar -ptx PLASMA-2.1.po sys/scripts/CONIO.4TH TXT
cat scripts/fileio.4th    	  | ./ac.jar -ptx PLASMA-2.1.po sys/scripts/FILEIO.4TH TXT
cat scripts/grlib.4th     	  | ./ac.jar -ptx PLASMA-2.1.po sys/scripts/GRLIB.4TH TXT
cat scripts/hgrlib.4th    	  | ./ac.jar -ptx PLASMA-2.1.po sys/scripts/HGRLIB.4TH TXT
cat scripts/int32.4th     	  | ./ac.jar -ptx PLASMA-2.1.po sys/scripts/INT32.4TH TXT
cat scripts/fpu.4th       	  | ./ac.jar -ptx PLASMA-2.1.po sys/scripts/FPU.4TH TXT

#rm -rf syspro
#mkdir syspro
#cat ../sysfiles/PRODOS#FF0000      | ./ac.jar -p   PLASMA-2.1.po syspro/PRODOS SYS
#cat rel/apple/CMD#061000           | ./ac.jar -p   PLASMA-2.1.po syspro/CMD BIN
#cat rel/apple/CMD128#061000        | ./ac.jar -p   PLASMA-2.1.po syspro/CMD128 BIN
#cat rel/apple/PLASMA.SYSTEM#FF2000 | ./ac.jar -p   PLASMA-2.1.po syspro/PLASMA.SYSTEM SYS
#cat rel/apple/PLVM.128#FF2000      | ./ac.jar -p   PLASMA-2.1.po syspro/PLVM.128 SYS
#cat rel/apple/PLVM16#FF2000        | ./ac.jar -p   PLASMA-2.1.po syspro/PLVM16 SYS
#cat ../doc/Editor.md               | ./ac.jar -ptx PLASMA-2.1.po syspro/EDITOR.README TXT

#mkdir syspro/sys
#cat rel/apple/FILEIO#FE1000        | ./ac.jar -p   PLASMA-2.1.po syspro/sys/FILEIO REL
#cat rel/apple/CONIO#FE1000         | ./ac.jar -p   PLASMA-2.1.po syspro/sys/CONIO REL
#cat rel/LINES#FE1000               | ./ac.jar -p   PLASMA-2.1.po syspro/sys/LINES REL
#cat rel/apple/HGRFONT#FE1000       | ./ac.jar -p   PLASMA-2.1.po syspro/sys/HGRFONT REL
#cat rel/apple/HGRTILE#FE1000       | ./ac.jar -p   PLASMA-2.1.po syspro/sys/HGRTILE REL
#cat rel/apple/HGRSPRITE#FE1000     | ./ac.jar -p   PLASMA-2.1.po syspro/sys/HGRSPRITE REL
#cat rel/apple/HGRLIB#FE1000        | ./ac.jar -p   PLASMA-2.1.po syspro/sys/HGRLIB REL
#cat rel/apple/GRLIB#FE1000         | ./ac.jar -p   PLASMA-2.1.po syspro/sys/GRLIB REL
#cat rel/apple/DGRLIB#FE1000        | ./ac.jar -p   PLASMA-2.1.po syspro/sys/DGRLIB REL
#cat rel/apple/COPY#FE1000          | ./ac.jar -p   PLASMA-2.1.po syspro/sys/COPY REL
#cat rel/apple/DEL#FE1000           | ./ac.jar -p   PLASMA-2.1.po syspro/sys/DEL REL
#cat rel/apple/REN#FE1000           | ./ac.jar -p   PLASMA-2.1.po syspro/sys/REN REL
#cat rel/apple/CAT#FE1000           | ./ac.jar -p   PLASMA-2.1.po syspro/sys/CAT REL
#cat rel/apple/NEWDIR#FE1000        | ./ac.jar -p   PLASMA-2.1.po syspro/sys/NEWDIR REL
#cat rel/apple/TYPE#FE1000          | ./ac.jar -p   PLASMA-2.1.po syspro/sys/TYPE REL
#cat rel/apple/MATCHFILES#FE1000    | ./ac.jar -p   PLASMA-2.1.po syspro/sys/MATCHFILES REL
#cat rel/ARGS#FE1000                | ./ac.jar -p   PLASMA-2.1.po syspro/sys/ARGS REL
#cat rel/ED#FE1000                  | ./ac.jar -p   PLASMA-2.1.po syspro/sys/ED REL
#cat rel/FIBER#FE1000               | ./ac.jar -p   PLASMA-2.1.po syspro/sys/FIBER REL
#cat rel/LONGJMP#FE1000             | ./ac.jar -p   PLASMA-2.1.po syspro/sys/LONGJMP REL
#cat rel/MEMMGR#FE1000              | ./ac.jar -p   PLASMA-2.1.po syspro/sys/MEMMGR REL
#cat rel/apple/MOUSE#FE1000         | ./ac.jar -p   PLASMA-2.1.po syspro/sys/MOUSE REL
#cat rel/apple/PORTIO#FE1000        | ./ac.jar -p   PLASMA-2.1.po syspro/sys/PORTIO REL
#cat rel/apple/JOYBUZZ#FE1000       | ./ac.jar -p   PLASMA-2.1.po syspro/sys/JOYBUZZ REL
#cat rel/apple/SNDSEQ#FE1000        | ./ac.jar -p   PLASMA-2.1.po syspro/sys/SNDSEQ REL
#cat rel/apple/JIT#FE1000           | ./ac.jar -p   PLASMA-2.1.po syspro/sys/JIT REL
#cat rel/apple/JIT16#FE1000         | ./ac.jar -p   PLASMA-2.1.po syspro/sys/JIT16 REL
#cat rel/apple/JITUNE#FE1000        | ./ac.jar -p   PLASMA-2.1.po syspro/sys/JITUNE REL
#cat rel/apple/ZIPCHIP#FE1000       | ./ac.jar -p   PLASMA-2.1.po syspro/sys/ZIPCHIP REL
#cat rel/LZ4#FE1000                 | ./ac.jar -p   PLASMA-2.1.po syspro/sys/LZ4 REL
#cat rel/INT32#FE1000               | ./ac.jar -p   PLASMA-2.1.po syspro/sys/INT32 REL

#rm -rf sysforth
#mkdir sysforth
#mkdir sysforth/sys
#cat rel/HRFORTH#FE1000             | ./ac.jar -p   PLASMA-2.1.po sysforth/sys/HRFORTH REL
#cat rel/HR2FORTH#FE1000            | ./ac.jar -p   PLASMA-2.1.po sysforth/sys/HR2FORTH REL
#cat rel/PLFORTH#FE1000             | ./ac.jar -p   PLASMA-2.1.po sysforth/sys/PLFORTH REL

#mkdir sysforth/sys/scripts
#cat scripts/plasma.4th    	  | ./ac.jar -ptx PLASMA-2.1.po sysforth/sys/scripts/PLASMA.4TH TXT
#cat scripts/conio.4th     	  | ./ac.jar -ptx PLASMA-2.1.po sysforth/sys/scripts/CONIO.4TH TXT
#cat scripts/fileio.4th    	  | ./ac.jar -ptx PLASMA-2.1.po sysforth/sys/scripts/FILEIO.4TH TXT
#cat scripts/grlib.4th     	  | ./ac.jar -ptx PLASMA-2.1.po sysforth/sys/scripts/GRLIB.4TH TXT
#cat scripts/hgrlib.4th    	  | ./ac.jar -ptx PLASMA-2.1.po sysforth/sys/scripts/HGRLIB.4TH TXT
#cat scripts/int32.4th     	  | ./ac.jar -ptx PLASMA-2.1.po sysforth/sys/scripts/INT32.4TH TXT
#cat scripts/fpu.4th       	  | ./ac.jar -ptx PLASMA-2.1.po sysforth/sys/scripts/FPU.4TH TXT

#rm -rf sysinet
#mkdir sysinet
#mkdir sysinet/sys
#cat rel/INET#FE1000                | ./ac.jar -p   PLASMA-2.1.po sysinet/sys/INET REL
#cat rel/DHCP#FE1000                | ./ac.jar -p   PLASMA-2.1.po sysinet/sys/DHCP REL
#cat rel/ETHERIP#FE1000             | ./ac.jar -p   PLASMA-2.1.po sysinet/sys/ETHERIP REL
#cat rel/apple/UTHERNET2#FE1000     | ./ac.jar -p   PLASMA-2.1.po sysinet/sys/UTHERNET2 REL
#cat rel/apple/UTHERNET#FE1000      | ./ac.jar -p   PLASMA-2.1.po sysinet/sys/UTHERNET REL
#cat rel/TFTPD#FE1000               | ./ac.jar -p   PLASMA-2.1.po sysinet/sys/TFTPD REL

#rm -rf fpsos
#mkdir fpsos
#cat ../sysfiles/SOS.KERNEL#0C0000  | ./ac.jar -p   PLASMA-2.1.po fpsos/SOS.KERNEL \$0C
#cat ../sysfiles/SOS.DRIVER#0C0000  | ./ac.jar -p   PLASMA-2.1.po fpsos/SOS.DRIVER \$0C
#cat rel/apple/SOS.INTERP#050000    | ./ac.jar -p   PLASMA-2.1.po fpsos/SOS.INTERP \$05
#cat rel/apple/SOS.CMD#FE1000       | ./ac.jar -p   PLASMA-2.1.po fpsos/SOS.CMD REL
#cat rel/apple/SOS.INTERPJIT#050000 | ./ac.jar -p   PLASMA-2.1.po fpsos/SOS.INTERPJIT \$05
#cat rel/apple/SOS.CMDJIT#FE1000    | ./ac.jar -p   PLASMA-2.1.po fpsos/SOS.CMDJIT REL

#mkdir fpsos/sys
#cat rel/apple/SOS#FE1000           | ./ac.jar -p   PLASMA-2.1.po fpsos/sys/SOS REL
#cat rel/apple/GRAFIX#FE1000        | ./ac.jar -p   PLASMA-2.1.po fpsos/sys/GRAFIX REL
#cat rel/FPSTR#FE1000               | ./ac.jar -p   PLASMA-2.1.po fpsos/sys/FPSTR REL
#cat rel/FPU#FE1000                 | ./ac.jar -p   PLASMA-2.1.po fpsos/sys/FPU REL
#cat rel/SANE#FE1000                | ./ac.jar -p   PLASMA-2.1.po fpsos/sys/SANE REL
#cat ../sysfiles/FP6502.CODE#060000 | ./ac.jar -p   PLASMA-2.1.po fpsos/sys/FP6502.CODE BIN
#cat ../sysfiles/ELEMS.CODE#060000  | ./ac.jar -p   PLASMA-2.1.po fpsos/sys/ELEMS.CODE BIN

#rm -rf demos
#mkdir demos
cat rel/INT32TEST#FE1000      | ./ac.jar -p   PLASMA-2.1.po demos/INT32TEST REL
cat rel/apple/CONIOTEST#FE1000 | ./ac.jar -p  PLASMA-2.1.po demos/CONIOTEST REL
cat rel/apple/ROD#FE1000      | ./ac.jar -p   PLASMA-2.1.po demos/ROD REL
cat rel/RPNCALC#FE1000        | ./ac.jar -p   PLASMA-2.1.po demos/RPNCALC REL
cat rel/LZ4CAT#FE1000         | ./ac.jar -p   PLASMA-2.1.po demos/LZ4CAT REL
cat ../doc/ROGUE.LZ4.BIN      | ./ac.jar -p   PLASMA-2.1.po demos/ROGUE.LZ4 BIN
cat rel/PRIMEGAP#FE1000       | ./ac.jar -p   PLASMA-2.1.po demos/PRIMEGAP REL

#mkdir demos/rogue
cat rel/ROGUE#FE1000        | ./ac.jar -p   PLASMA-2.1.po demos/rogue/ROGUE REL
cat rel/ROGUECOMBAT#FE1000  | ./ac.jar -p   PLASMA-2.1.po demos/rogue/ROGUECOMBAT REL
cat rel/ROGUEMAP#FE1000     | ./ac.jar -p   PLASMA-2.1.po demos/rogue/ROGUEMAP REL
cat samplesrc/LEVEL0#040000 | ./ac.jar -ptx PLASMA-2.1.po demos/rogue/LEVEL0 TXT
cat samplesrc/LEVEL1#040000 | ./ac.jar -ptx PLASMA-2.1.po demos/rogue/LEVEL1 TXT

#mkdir demos/music
cat rel/apple/PLAYSEQ#FE1000  | ./ac.jar -p   PLASMA-2.1.po demos/music/PLAYSEQ REL
cat mockingboard/ultima3.seq  | ./ac.jar -p   PLASMA-2.1.po demos/music/ULTIMA3.SEQ BIN
cat mockingboard/startrek.seq | ./ac.jar -p   PLASMA-2.1.po demos/music/STARTREK.SEQ BIN

#mkdir demos/net
cat rel/HTTPD#FE1000     | ./ac.jar -p   PLASMA-2.1.po demos/net/HTTPD REL
cat samplesrc/index.html | ./ac.jar -ptx PLASMA-2.1.po demos/net/INDEX.HTML TXT

#mkdir demos/apple2
cat rel/apple/TILETEST#FE1000 | ./ac.jar -p   PLASMA-2.1.po demos/apple2/TILETEST REL
cat rel/apple/HGRTEST#FE1000  | ./ac.jar -p   PLASMA-2.1.po demos/apple2/HGRTEST REL
cat rel/apple/GRTEST#FE1000   | ./ac.jar -p   PLASMA-2.1.po demos/apple2/GRTEST REL
cat rel/apple/DGRTEST#FE1000  | ./ac.jar -p   PLASMA-2.1.po demos/apple2/DGRTEST REL

#mkdir demos/apple2/spiders
cat rel/apple/SFM#FE1000     | ./ac.jar -p   PLASMA-2.1.po demos/apple2/spiders/SFM REL
cat rel/apple/SFMSPRT#FE1000 | ./ac.jar -p   PLASMA-2.1.po demos/apple2/spiders/SFMSPRT REL

#mkdir demos/apple2/sdutils
cat rel/apple/SPIPORT#FE1000     | ./ac.jar -p   PLASMA-2.1.po demos/apple2/sdutils/SPIPORT REL
cat rel/apple/SDFAT#FE1000       | ./ac.jar -p   PLASMA-2.1.po demos/apple2/sdutils/SDFAT REL
cat rel/apple/FATCAT#FE1000      | ./ac.jar -p   PLASMA-2.1.po demos/apple2/sdutils/FATCAT REL
cat rel/apple/FATGET#FE1000      | ./ac.jar -p   PLASMA-2.1.po demos/apple2/sdutils/FATGET REL
cat rel/apple/FATPUT#FE1000      | ./ac.jar -p   PLASMA-2.1.po demos/apple2/sdutils/FATPUT REL
cat rel/apple/FATREADDSK#FE1000  | ./ac.jar -p   PLASMA-2.1.po demos/apple2/sdutils/FATREADDSK REL
cat rel/apple/FATWRITEDSK#FE1000 | ./ac.jar -p   PLASMA-2.1.po demos/apple2/sdutils/FATWRITEDSK REL

#mkdir demos/apple3
cat rel/apple/GFXDEMO#FE1000    | ./ac.jar -p   PLASMA-2.1.po demos/apple3/GFXDEMO REL
cat samplesrc/APPLE3.PIX#060000 | ./ac.jar -p   PLASMA-2.1.po demos/apple3/APPLE3.PIX BIN

#rm -rf bld
#mkdir bld
cat rel/PLASM#FE1000        | ./ac.jar -p   PLASMA-2.1.po bld/PLASM REL
cat rel/CODEOPT#FE1000      | ./ac.jar -p   PLASMA-2.1.po bld/CODEOPT REL

#mkdir bld/samples
cat samplesrc/hello.pla     | ./ac.jar -ptx PLASMA-2.1.po bld/samples/HELLO.PLA TXT
cat samplesrc/int32test.pla | ./ac.jar -ptx PLASMA-2.1.po bld/samples/INT32TEST.PLA TXT
cat samplesrc/coniotest.pla | ./ac.jar -ptx PLASMA-2.1.po bld/samples/CONIOTEST.PLA TXT
cat samplesrc/grtest.pla    | ./ac.jar -ptx PLASMA-2.1.po bld/samples/GRTEST.PLA TXT
cat samplesrc/dgrtest.pla   | ./ac.jar -ptx PLASMA-2.1.po bld/samples/DGRTEST.PLA TXT
cat samplesrc/hgrtest.pla   | ./ac.jar -ptx PLASMA-2.1.po bld/samples/HGRTEST.PLA TXT
cat samplesrc/tiletest.pla  | ./ac.jar -ptx PLASMA-2.1.po bld/samples/TILETEST.PLA TXT
cat samplesrc/fibertest.pla | ./ac.jar -ptx PLASMA-2.1.po bld/samples/FIBERTEST.PLA TXT
cat samplesrc/mousetest.pla | ./ac.jar -ptx PLASMA-2.1.po bld/samples/MOUSETEST.PLA TXT
cat samplesrc/memtest.pla   | ./ac.jar -ptx PLASMA-2.1.po bld/samples/MEMTEST.PLA TXT
cat samplesrc/rod.pla       | ./ac.jar -ptx PLASMA-2.1.po bld/samples/ROD.PLA TXT
cat samplesrc/sieve.pla     | ./ac.jar -ptx PLASMA-2.1.po bld/samples/SIEVE.PLA TXT
cat samplesrc/test.pla      | ./ac.jar -ptx PLASMA-2.1.po bld/samples/TEST.PLA TXT
cat samplesrc/testlib.pla   | ./ac.jar -ptx PLASMA-2.1.po bld/samples/TESTLIB.PLA TXT
cat samplesrc/playseq.pla   | ./ac.jar -ptx PLASMA-2.1.po bld/samples/PLAYSEQ.PLA TXT
cat samplesrc/rpncalc.pla   | ./ac.jar -ptx PLASMA-2.1.po bld/samples/RPNCALC.PLA TXT
cat samplesrc/fatcat.pla    | ./ac.jar -ptx PLASMA-2.1.po bld/samples/FATCAT.PLA TXT
cat samplesrc/gfxdemo.pla   | ./ac.jar -ptx PLASMA-2.1.po bld/samples/GFXDEMO.PLA TXT
cat samplesrc/lz4cat.pla    | ./ac.jar -ptx PLASMA-2.1.po bld/samples/LZ4CAT.PLA TXT
cat samplesrc/sfm.pla       | ./ac.jar -ptx PLASMA-2.1.po bld/samples/SFM.PLA TXT
cat samplesrc/sfmsprt.pla   | ./ac.jar -ptx PLASMA-2.1.po bld/samples/SFMSPRT.PLA TXT
cat samplesrc/fppow.pla     | ./ac.jar -ptx PLASMA-2.1.po bld/samples/FPPOW.PLA TXT
cat utilsrc/apple/mon.pla   | ./ac.jar -ptx PLASMA-2.1.po bld/samples/MON.PLA TXT
cat utilsrc/apple/zipchip.pla | ./ac.jar -ptx PLASMA-2.1.po bld/samples/ZIPCHIP.PLA TXT

#mkdir bld/scripts
cat scripts/rod.4th       | ./ac.jar -ptx PLASMA-2.1.po bld/scripts/ROD.4TH TXT
cat scripts/bounce.4th    | ./ac.jar -ptx PLASMA-2.1.po bld/scripts/BOUNCE.4TH TXT
cat scripts/hrbounce.4th  | ./ac.jar -ptx PLASMA-2.1.po bld/scripts/HRBOUNCE.4TH TXT

#mkdir bld/examples
#cat samplesrc/examples/ex.1.pla  bld/examples/EX.1.PLA TXT
#cat samplesrc/examples/ex.2.pla  bld/examples/EX.2.PLA TXT
#cat samplesrc/examples/ex.3.pla  bld/examples/EX.3.PLA TXT
#cat samplesrc/examples/ex.4.pla  bld/examples/EX.4.PLA TXT
#cat samplesrc/examples/ex.5.pla  bld/examples/EX.5.PLA TXT
#cat samplesrc/examples/ex.6.pla  bld/examples/EX.6.PLA TXT
#cat samplesrc/examples/ex.7.pla  bld/examples/EX.7.PLA TXT
#cat samplesrc/examples/ex.8.pla  bld/examples/EX.8.PLA TXT
#cat samplesrc/examples/ex.9.pla  bld/examples/EX.9.PLA TXT
#cat samplesrc/examples/ex.10.pla bld/examples/EX.10.PLA TXT
#cat samplesrc/examples/ex.11.pla bld/examples/EX.11.PLA TXT
#cat samplesrc/examples/ex.12.pla bld/examples/EX.12.PLA TXT
#cat samplesrc/examples/ex.13.pla bld/examples/EX.13.PLA TXT
#cat samplesrc/examples/ex.14.pla bld/examples/EX.14.PLA TXT
#cat samplesrc/examples/ex.15.pla bld/examples/EX.15.PLA TXT
#cat samplesrc/examples/ex.16.pla bld/examples/EX.16.PLA TXT
#cat samplesrc/examples/ex.17.pla bld/examples/EX.17.PLA TXT

#mkdir bld/inc
cat inc/args.plh           | ./ac.jar -ptx PLASMA-2.1.po bld/inc/ARGS.PLH TXT
cat inc/matchfiles.plh     | ./ac.jar -ptx PLASMA-2.1.po bld/inc/MATCHFILES.PLH TXT
cat inc/cmdsys.plh         | ./ac.jar -ptx PLASMA-2.1.po bld/inc/CMDSYS.PLH TXT
cat inc/conio.plh          | ./ac.jar -ptx PLASMA-2.1.po bld/inc/CONIO.PLH TXT
cat inc/lines.plh          | ./ac.jar -ptx PLASMA-2.1.po bld/inc/LINES.PLH TXT
cat inc/hgrfont.plh        | ./ac.jar -ptx PLASMA-2.1.po bld/inc/HGRFONT.PLH TXT
cat inc/hgrtile.plh        | ./ac.jar -ptx PLASMA-2.1.po bld/inc/HGRTILE.PLH TXT
cat inc/hgrsprite.plh      | ./ac.jar -ptx PLASMA-2.1.po bld/inc/HGRSPRITE.PLH TXT
cat inc/hgrlib.plh         | ./ac.jar -ptx PLASMA-2.1.po bld/inc/HGRLIB.PLH TXT
cat inc/grlib.plh          | ./ac.jar -ptx PLASMA-2.1.po bld/inc/GRLIB.PLH TXT
cat inc/dgrlib.plh         | ./ac.jar -ptx PLASMA-2.1.po bld/inc/DGRLIB.PLH TXT
cat inc/fiber.plh          | ./ac.jar -ptx PLASMA-2.1.po bld/inc/FIBER.PLH TXT
cat inc/fileio.plh         | ./ac.jar -ptx PLASMA-2.1.po bld/inc/FILEIO.PLH TXT
cat inc/int32.plh          | ./ac.jar -ptx PLASMA-2.1.po bld/inc/INT32.PLH TXT
cat inc/fpstr.plh          | ./ac.jar -ptx PLASMA-2.1.po bld/inc/FPSTR.PLH TXT
cat inc/fpu.plh            | ./ac.jar -ptx PLASMA-2.1.po bld/inc/FPU.PLH TXT
cat inc/mouse.plh          | ./ac.jar -ptx PLASMA-2.1.po bld/inc/MOUSE.PLH TXT
cat inc/inet.plh           | ./ac.jar -ptx PLASMA-2.1.po bld/inc/INET.PLH TXT
cat inc/longjmp.plh        | ./ac.jar -ptx PLASMA-2.1.po bld/inc/LONGJMP.PLH TXT
cat inc/memmgr.plh         | ./ac.jar -ptx PLASMA-2.1.po bld/inc/MEMMGR.PLH TXT
cat inc/sane.plh           | ./ac.jar -ptx PLASMA-2.1.po bld/inc/SANE.PLH TXT
cat inc/joybuzz.plh        | ./ac.jar -ptx PLASMA-2.1.po bld/inc/JOYBUZZ.PLH TXT
cat inc/portio.plh         | ./ac.jar -ptx PLASMA-2.1.po bld/inc/PORTIO.PLH TXT
cat inc/sdfat.plh          | ./ac.jar -ptx PLASMA-2.1.po bld/inc/SDFAT.PLH TXT
cat inc/sndseq.plh         | ./ac.jar -ptx PLASMA-2.1.po bld/inc/SNDSEQ.PLH TXT
cat inc/spiport.plh        | ./ac.jar -ptx PLASMA-2.1.po bld/inc/SPIPORT.PLH TXT
cat inc/testlib.plh        | ./ac.jar -ptx PLASMA-2.1.po bld/inc/TESTLIB.PLH TXT
cat inc/grafix.plh         | ./ac.jar -ptx PLASMA-2.1.po bld/inc/GRAFIX.PLH TXT
cat inc/lz4.plh            | ./ac.jar -ptx PLASMA-2.1.po bld/inc/LZ4.PLH TXT
cat vmsrc/apple/plvmzp.inc | ./ac.jar -ptx PLASMA-2.1.po bld/inc/PLVMZP.INC TXT
