#!/bin/bash
PO_IMAGE=PLASMA-2.20.po
./mkrel
cp ../sysfiles/BLANK32M.po $PO_IMAGE
java -jar ac.jar -n $PO_IMAGE PLASMA2
cat ../sysfiles/PRODOS#FF0000      | java -jar ac.jar -p   $PO_IMAGE PRODOS SYS
cat rel/apple/CMD#061000           | java -jar ac.jar -p   $PO_IMAGE CMD BIN $1000
cat rel/apple/CMD.128#061000       | java -jar ac.jar -p   $PO_IMAGE CMD.128 BIN $1000
cat rel/apple/PLASMA.SYSTEM#FF2000 | java -jar ac.jar -p   $PO_IMAGE PLASMA.SYSTEM SYS
cat rel/apple/PLVM.128#FF2000      | java -jar ac.jar -p   $PO_IMAGE PLVM.128 SYS
cat rel/apple/PLVM16#FF2000        | java -jar ac.jar -p   $PO_IMAGE PLVM16 SYS
cat ../doc/Editor.md               | java -jar ac.jar -ptx $PO_IMAGE EDITOR.README TXT

#mkdir sys
cat rel/apple/FILEIO#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/FILEIO REL
cat rel/apple/CONIO#FE1000         | java -jar ac.jar -p   $PO_IMAGE sys/CONIO REL
cat rel/apple/VBLANK#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/VBLANK REL
cat rel/apple/INITSLOT#FE1000      | java -jar ac.jar -p   $PO_IMAGE sys/INITSLOT REL
cat rel/LINES#FE1000               | java -jar ac.jar -p   $PO_IMAGE sys/LINES REL
cat rel/apple/HGRFONT#FE1000       | java -jar ac.jar -p   $PO_IMAGE sys/HGRFONT REL
cat rel/apple/HGRTILE#FE1000       | java -jar ac.jar -p   $PO_IMAGE sys/HGRTILE REL
cat rel/apple/HGRSPRITE#FE1000     | java -jar ac.jar -p   $PO_IMAGE sys/HGRSPRITE REL
cat rel/apple/HGRLIB#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/HGRLIB REL
cat rel/apple/GRLIB#FE1000         | java -jar ac.jar -p   $PO_IMAGE sys/GRLIB REL
cat rel/apple/DGRLIB#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/DGRLIB REL
cat rel/apple/COPY#FE1000          | java -jar ac.jar -p   $PO_IMAGE sys/COPY REL
cat rel/apple/DEL#FE1000           | java -jar ac.jar -p   $PO_IMAGE sys/DEL REL
cat rel/apple/REN#FE1000           | java -jar ac.jar -p   $PO_IMAGE sys/REN REL
cat rel/apple/CAT#FE1000           | java -jar ac.jar -p   $PO_IMAGE sys/CAT REL
cat rel/apple/NEWDIR#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/NEWDIR REL
cat rel/apple/TYPE#FE1000          | java -jar ac.jar -p   $PO_IMAGE sys/TYPE REL
cat rel/apple/MATCHFILES#FE1000    | java -jar ac.jar -p   $PO_IMAGE sys/MATCHFILES REL
cat rel/ARGS#FE1000                | java -jar ac.jar -p   $PO_IMAGE sys/ARGS REL
cat rel/ED#FE1000                  | java -jar ac.jar -p   $PO_IMAGE sys/ED REL
cat rel/FIBER#FE1000               | java -jar ac.jar -p   $PO_IMAGE sys/FIBER REL
cat rel/LONGJMP#FE1000             | java -jar ac.jar -p   $PO_IMAGE sys/LONGJMP REL
cat rel/MEMMGR#FE1000              | java -jar ac.jar -p   $PO_IMAGE sys/MEMMGR REL
cat rel/INET#FE1000                | java -jar ac.jar -p   $PO_IMAGE sys/INET REL
cat rel/DHCP#FE1000                | java -jar ac.jar -p   $PO_IMAGE sys/DHCP REL
cat rel/ETHERIP#FE1000             | java -jar ac.jar -p   $PO_IMAGE sys/ETHERIP REL
cat rel/apple/MOUSE#FE1000         | java -jar ac.jar -p   $PO_IMAGE sys/MOUSE REL
cat rel/apple/UTHERNET2#FE1000     | java -jar ac.jar -p   $PO_IMAGE sys/UTHERNET2 REL
cat rel/apple/UTHERNET#FE1000      | java -jar ac.jar -p   $PO_IMAGE sys/UTHERNET REL
cat rel/apple/PORTIO#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/PORTIO REL
cat rel/apple/JOYBUZZ#FE1000       | java -jar ac.jar -p   $PO_IMAGE sys/JOYBUZZ REL
cat rel/apple/SNDSEQ#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/SNDSEQ REL
cat rel/apple/JIT#FE1000           | java -jar ac.jar -p   $PO_IMAGE sys/JIT REL
cat rel/apple/JIT16#FE1000         | java -jar ac.jar -p   $PO_IMAGE sys/JIT16 REL
cat rel/apple/JITUNE#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/JITUNE REL
cat rel/apple/ZIPCHIP#FE1000       | java -jar ac.jar -p   $PO_IMAGE sys/ZIPCHIP REL
cat rel/LZ4#FE1000                 | java -jar ac.jar -p   $PO_IMAGE sys/LZ4 REL
cat rel/TFTPD#FE1000               | java -jar ac.jar -p   $PO_IMAGE sys/TFTPD REL
cat rel/INT32#FE1000               | java -jar ac.jar -p   $PO_IMAGE sys/INT32 REL
cat rel/FPSTR#FE1000               | java -jar ac.jar -p   $PO_IMAGE sys/FPSTR REL
cat rel/FPU#FE1000                 | java -jar ac.jar -p   $PO_IMAGE sys/FPU REL
cat rel/SANE#FE1000                | java -jar ac.jar -p   $PO_IMAGE sys/SANE REL
cat ../sysfiles/FP6502.CODE#060000 | java -jar ac.jar -p   $PO_IMAGE sys/FP6502.CODE BIN
cat ../sysfiles/ELEMS.CODE#060000  | java -jar ac.jar -p   $PO_IMAGE sys/ELEMS.CODE BIN
cat rel/apple/SOS#FE1000           | java -jar ac.jar -p   $PO_IMAGE sys/SOS REL
cat rel/apple/GRAFIX#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/GRAFIX REL
cat rel/HRFORTH#FE1000             | java -jar ac.jar -p   $PO_IMAGE sys/HRFORTH REL
cat rel/HR2FORTH#FE1000            | java -jar ac.jar -p   $PO_IMAGE sys/HR2FORTH REL
cat rel/TX2FORTH#FE1000            | java -jar ac.jar -p   $PO_IMAGE sys/TX2FORTH REL
cat rel/PLFORTH#FE1000             | java -jar ac.jar -p   $PO_IMAGE sys/PLFORTH REL

#mkdir sys/scripts
cat scripts/hdinstall.4th     | java -jar ac.jar -ptx $PO_IMAGE HDINSTALL.4TH TXT
cat scripts/plasma.4th        | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/PLASMA.4TH TXT
cat scripts/machid.4th        | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/MACHID.4TH TXT
cat scripts/conio.4th         | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/CONIO.4TH TXT
cat scripts/fileio.4th        | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/FILEIO.4TH TXT
cat scripts/grlib.4th         | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/GRLIB.4TH TXT
cat scripts/dgrlib.4th        | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/DGRLIB.4TH TXT
cat scripts/hgrlib.4th        | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/HGRLIB.4TH TXT
cat scripts/int32.4th         | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/INT32.4TH TXT
cat scripts/fpu.4th           | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/FPU.4TH TXT

#rm -rf syspro
#mkdir syspro
#cat ../sysfiles/PRODOS#FF0000      | java -jar ac.jar -p   $PO_IMAGE syspro/PRODOS SYS
#cat rel/apple/CMD#061000           | java -jar ac.jar -p   $PO_IMAGE syspro/CMD BIN
#cat rel/apple/CMD128#061000        | java -jar ac.jar -p   $PO_IMAGE syspro/CMD128 BIN
#cat rel/apple/PLASMA.SYSTEM#FF2000 | java -jar ac.jar -p   $PO_IMAGE syspro/PLASMA.SYSTEM SYS
#cat rel/apple/PLVM.128#FF2000      | java -jar ac.jar -p   $PO_IMAGE syspro/PLVM.128 SYS
#cat rel/apple/PLVM16#FF2000        | java -jar ac.jar -p   $PO_IMAGE syspro/PLVM16 SYS
#cat ../doc/Editor.md               | java -jar ac.jar -ptx $PO_IMAGE syspro/EDITOR.README TXT

#mkdir syspro/sys
#cat rel/apple/FILEIO#FE1000        | java -jar ac.jar -p   $PO_IMAGE syspro/sys/FILEIO REL
#cat rel/apple/CONIO#FE1000         | java -jar ac.jar -p   $PO_IMAGE syspro/sys/CONIO REL
#cat rel/LINES#FE1000               | java -jar ac.jar -p   $PO_IMAGE syspro/sys/LINES REL
#cat rel/apple/HGRFONT#FE1000       | java -jar ac.jar -p   $PO_IMAGE syspro/sys/HGRFONT REL
#cat rel/apple/HGRTILE#FE1000       | java -jar ac.jar -p   $PO_IMAGE syspro/sys/HGRTILE REL
#cat rel/apple/HGRSPRITE#FE1000     | java -jar ac.jar -p   $PO_IMAGE syspro/sys/HGRSPRITE REL
#cat rel/apple/HGRLIB#FE1000        | java -jar ac.jar -p   $PO_IMAGE syspro/sys/HGRLIB REL
#cat rel/apple/GRLIB#FE1000         | java -jar ac.jar -p   $PO_IMAGE syspro/sys/GRLIB REL
#cat rel/apple/DGRLIB#FE1000        | java -jar ac.jar -p   $PO_IMAGE syspro/sys/DGRLIB REL
#cat rel/apple/COPY#FE1000          | java -jar ac.jar -p   $PO_IMAGE syspro/sys/COPY REL
#cat rel/apple/DEL#FE1000           | java -jar ac.jar -p   $PO_IMAGE syspro/sys/DEL REL
#cat rel/apple/REN#FE1000           | java -jar ac.jar -p   $PO_IMAGE syspro/sys/REN REL
#cat rel/apple/CAT#FE1000           | java -jar ac.jar -p   $PO_IMAGE syspro/sys/CAT REL
#cat rel/apple/NEWDIR#FE1000        | java -jar ac.jar -p   $PO_IMAGE syspro/sys/NEWDIR REL
#cat rel/apple/TYPE#FE1000          | java -jar ac.jar -p   $PO_IMAGE syspro/sys/TYPE REL
#cat rel/apple/MATCHFILES#FE1000    | java -jar ac.jar -p   $PO_IMAGE syspro/sys/MATCHFILES REL
#cat rel/ARGS#FE1000                | java -jar ac.jar -p   $PO_IMAGE syspro/sys/ARGS REL
#cat rel/ED#FE1000                  | java -jar ac.jar -p   $PO_IMAGE syspro/sys/ED REL
#cat rel/FIBER#FE1000               | java -jar ac.jar -p   $PO_IMAGE syspro/sys/FIBER REL
#cat rel/LONGJMP#FE1000             | java -jar ac.jar -p   $PO_IMAGE syspro/sys/LONGJMP REL
#cat rel/MEMMGR#FE1000              | java -jar ac.jar -p   $PO_IMAGE syspro/sys/MEMMGR REL
#cat rel/apple/MOUSE#FE1000         | java -jar ac.jar -p   $PO_IMAGE syspro/sys/MOUSE REL
#cat rel/apple/PORTIO#FE1000        | java -jar ac.jar -p   $PO_IMAGE syspro/sys/PORTIO REL
#cat rel/apple/JOYBUZZ#FE1000       | java -jar ac.jar -p   $PO_IMAGE syspro/sys/JOYBUZZ REL
#cat rel/apple/SNDSEQ#FE1000        | java -jar ac.jar -p   $PO_IMAGE syspro/sys/SNDSEQ REL
#cat rel/apple/JIT#FE1000           | java -jar ac.jar -p   $PO_IMAGE syspro/sys/JIT REL
#cat rel/apple/JIT16#FE1000         | java -jar ac.jar -p   $PO_IMAGE syspro/sys/JIT16 REL
#cat rel/apple/JITUNE#FE1000        | java -jar ac.jar -p   $PO_IMAGE syspro/sys/JITUNE REL
#cat rel/apple/ZIPCHIP#FE1000       | java -jar ac.jar -p   $PO_IMAGE syspro/sys/ZIPCHIP REL
#cat rel/LZ4#FE1000                 | java -jar ac.jar -p   $PO_IMAGE syspro/sys/LZ4 REL
#cat rel/INT32#FE1000               | java -jar ac.jar -p   $PO_IMAGE syspro/sys/INT32 REL

#rm -rf sysforth
#mkdir sysforth
#mkdir sysforth/sys
#cat rel/HRFORTH#FE1000             | java -jar ac.jar -p   $PO_IMAGE sysforth/sys/HRFORTH REL
#cat rel/HR2FORTH#FE1000            | java -jar ac.jar -p   $PO_IMAGE sysforth/sys/HR2FORTH REL
#cat rel/PLFORTH#FE1000             | java -jar ac.jar -p   $PO_IMAGE sysforth/sys/PLFORTH REL

#mkdir sysforth/sys/scripts
#cat scripts/plasma.4th       | java -jar ac.jar -ptx $PO_IMAGE sysforth/sys/scripts/PLASMA.4TH TXT
#cat scripts/conio.4th        | java -jar ac.jar -ptx $PO_IMAGE sysforth/sys/scripts/CONIO.4TH TXT
#cat scripts/fileio.4th       | java -jar ac.jar -ptx $PO_IMAGE sysforth/sys/scripts/FILEIO.4TH TXT
#cat scripts/grlib.4th        | java -jar ac.jar -ptx $PO_IMAGE sysforth/sys/scripts/GRLIB.4TH TXT
#cat scripts/hgrlib.4th       | java -jar ac.jar -ptx $PO_IMAGE sysforth/sys/scripts/HGRLIB.4TH TXT
#cat scripts/int32.4th        | java -jar ac.jar -ptx $PO_IMAGE sysforth/sys/scripts/INT32.4TH TXT
#cat scripts/fpu.4th          | java -jar ac.jar -ptx $PO_IMAGE sysforth/sys/scripts/FPU.4TH TXT

#rm -rf sysinet
#mkdir sysinet
#mkdir sysinet/sys
#cat rel/INET#FE1000                | java -jar ac.jar -p   $PO_IMAGE sysinet/sys/INET REL
#cat rel/DHCP#FE1000                | java -jar ac.jar -p   $PO_IMAGE sysinet/sys/DHCP REL
#cat rel/ETHERIP#FE1000             | java -jar ac.jar -p   $PO_IMAGE sysinet/sys/ETHERIP REL
#cat rel/apple/UTHERNET2#FE1000     | java -jar ac.jar -p   $PO_IMAGE sysinet/sys/UTHERNET2 REL
#cat rel/apple/UTHERNET#FE1000      | java -jar ac.jar -p   $PO_IMAGE sysinet/sys/UTHERNET REL
#cat rel/TFTPD#FE1000               | java -jar ac.jar -p   $PO_IMAGE sysinet/sys/TFTPD REL

#rm -rf fpsos
#mkdir fpsos
#cat ../sysfiles/SOS.KERNEL#0C0000  | java -jar ac.jar -p   $PO_IMAGE fpsos/SOS.KERNEL \$0C
#cat ../sysfiles/SOS.DRIVER#0C0000  | java -jar ac.jar -p   $PO_IMAGE fpsos/SOS.DRIVER \$0C
#cat rel/apple/SOS.INTERP#050000    | java -jar ac.jar -p   $PO_IMAGE fpsos/SOS.INTERP \$05
#cat rel/apple/SOS.CMD#FE1000       | java -jar ac.jar -p   $PO_IMAGE fpsos/SOS.CMD REL
#cat rel/apple/SOS.INTERPJIT#050000 | java -jar ac.jar -p   $PO_IMAGE fpsos/SOS.INTERPJIT \$05
#cat rel/apple/SOS.CMDJIT#FE1000    | java -jar ac.jar -p   $PO_IMAGE fpsos/SOS.CMDJIT REL

#mkdir fpsos/sys
#cat rel/apple/SOS#FE1000           | java -jar ac.jar -p   $PO_IMAGE fpsos/sys/SOS REL
#cat rel/apple/GRAFIX#FE1000        | java -jar ac.jar -p   $PO_IMAGE fpsos/sys/GRAFIX REL
#cat rel/FPSTR#FE1000               | java -jar ac.jar -p   $PO_IMAGE fpsos/sys/FPSTR REL
#cat rel/FPU#FE1000                 | java -jar ac.jar -p   $PO_IMAGE fpsos/sys/FPU REL
#cat rel/SANE#FE1000                | java -jar ac.jar -p   $PO_IMAGE fpsos/sys/SANE REL
#cat ../sysfiles/FP6502.CODE#060000 | java -jar ac.jar -p   $PO_IMAGE fpsos/sys/FP6502.CODE BIN
#cat ../sysfiles/ELEMS.CODE#060000  | java -jar ac.jar -p   $PO_IMAGE fpsos/sys/ELEMS.CODE BIN

#rm -rf demos
#mkdir demos
cat rel/INT32TEST#FE1000      | java -jar ac.jar -p   $PO_IMAGE demos/INT32TEST REL
cat rel/apple/CONIOTEST#FE1000 | java -jar ac.jar -p  $PO_IMAGE demos/CONIOTEST REL
cat rel/apple/ROD#FE1000      | java -jar ac.jar -p   $PO_IMAGE demos/ROD REL
cat rel/RPNCALC#FE1000        | java -jar ac.jar -p   $PO_IMAGE demos/RPNCALC REL
cat rel/LZ4CAT#FE1000         | java -jar ac.jar -p   $PO_IMAGE demos/LZ4CAT REL
cat ../doc/ROGUE.LZ4.BIN      | java -jar ac.jar -p   $PO_IMAGE demos/ROGUE.LZ4 BIN
cat rel/PRIMEGAP#FE1000       | java -jar ac.jar -p   $PO_IMAGE demos/PRIMEGAP REL

#mkdir demos/rogue
cat rel/ROGUE#FE1000        | java -jar ac.jar -p   $PO_IMAGE demos/rogue/ROGUE REL
cat rel/ROGUECOMBAT#FE1000  | java -jar ac.jar -p   $PO_IMAGE demos/rogue/ROGUECOMBAT REL
cat rel/ROGUEMAP#FE1000     | java -jar ac.jar -p   $PO_IMAGE demos/rogue/ROGUEMAP REL
cat samplesrc/LEVEL0#040000 | java -jar ac.jar -ptx $PO_IMAGE demos/rogue/LEVEL0 TXT
cat samplesrc/LEVEL1#040000 | java -jar ac.jar -ptx $PO_IMAGE demos/rogue/LEVEL1 TXT

#mkdir demos/music
cat rel/apple/PLAYSEQ#FE1000  | java -jar ac.jar -p   $PO_IMAGE demos/music/PLAYSEQ REL
cat mockingboard/ultima3.seq  | java -jar ac.jar -p   $PO_IMAGE demos/music/ULTIMA3.SEQ BIN
cat mockingboard/startrek.seq | java -jar ac.jar -p   $PO_IMAGE demos/music/STARTREK.SEQ BIN

#mkdir demos/net
cat rel/HTTPD#FE1000     | java -jar ac.jar -p   $PO_IMAGE demos/net/HTTPD REL
cat samplesrc/index.html | java -jar ac.jar -ptx $PO_IMAGE demos/net/INDEX.HTML TXT

#mkdir demos/apple2
cat rel/apple/TILETEST#FE1000 | java -jar ac.jar -p   $PO_IMAGE demos/apple2/TILETEST REL
cat rel/apple/HGRTEST#FE1000  | java -jar ac.jar -p   $PO_IMAGE demos/apple2/HGRTEST REL
cat rel/apple/GRTEST#FE1000   | java -jar ac.jar -p   $PO_IMAGE demos/apple2/GRTEST REL
cat rel/apple/DGRTEST#FE1000  | java -jar ac.jar -p   $PO_IMAGE demos/apple2/DGRTEST REL

#mkdir demos/apple2/spiders
cat rel/apple/SFM#FE1000     | java -jar ac.jar -p   $PO_IMAGE demos/apple2/spiders/SFM REL
cat rel/apple/SFMSPRT#FE1000 | java -jar ac.jar -p   $PO_IMAGE demos/apple2/spiders/SFMSPRT REL

#mkdir demos/apple2/sdutils
cat rel/apple/SPIPORT#FE1000     | java -jar ac.jar -p   $PO_IMAGE demos/apple2/sdutils/SPIPORT REL
cat rel/apple/SDFAT#FE1000       | java -jar ac.jar -p   $PO_IMAGE demos/apple2/sdutils/SDFAT REL
cat rel/apple/FATCAT#FE1000      | java -jar ac.jar -p   $PO_IMAGE demos/apple2/sdutils/FATCAT REL
cat rel/apple/FATGET#FE1000      | java -jar ac.jar -p   $PO_IMAGE demos/apple2/sdutils/FATGET REL
cat rel/apple/FATPUT#FE1000      | java -jar ac.jar -p   $PO_IMAGE demos/apple2/sdutils/FATPUT REL
cat rel/apple/FATREADDSK#FE1000  | java -jar ac.jar -p   $PO_IMAGE demos/apple2/sdutils/FATREADDSK REL
cat rel/apple/FATWRITEDSK#FE1000 | java -jar ac.jar -p   $PO_IMAGE demos/apple2/sdutils/FATWRITEDSK REL

#mkdir demos/apple3
cat rel/apple/GFXDEMO#FE1000    | java -jar ac.jar -p   $PO_IMAGE demos/apple3/GFXDEMO REL
cat samplesrc/APPLE3.PIX#060000 | java -jar ac.jar -p   $PO_IMAGE demos/apple3/APPLE3.PIX BIN

#rm -rf bld
#mkdir bld
cat rel/PLASM#FE1000        | java -jar ac.jar -p   $PO_IMAGE bld/PLASM REL
cat rel/CODEOPT#FE1000      | java -jar ac.jar -p   $PO_IMAGE bld/CODEOPT REL

#mkdir bld/samples
cat samplesrc/hello.pla     | java -jar ac.jar -ptx $PO_IMAGE bld/samples/HELLO.PLA TXT
cat samplesrc/int32test.pla | java -jar ac.jar -ptx $PO_IMAGE bld/samples/INT32TEST.PLA TXT
cat samplesrc/coniotest.pla | java -jar ac.jar -ptx $PO_IMAGE bld/samples/CONIOTEST.PLA TXT
cat samplesrc/grtest.pla    | java -jar ac.jar -ptx $PO_IMAGE bld/samples/GRTEST.PLA TXT
cat samplesrc/dgrtest.pla   | java -jar ac.jar -ptx $PO_IMAGE bld/samples/DGRTEST.PLA TXT
cat samplesrc/hgrtest.pla   | java -jar ac.jar -ptx $PO_IMAGE bld/samples/HGRTEST.PLA TXT
cat samplesrc/tiletest.pla  | java -jar ac.jar -ptx $PO_IMAGE bld/samples/TILETEST.PLA TXT
cat samplesrc/fibertest.pla | java -jar ac.jar -ptx $PO_IMAGE bld/samples/FIBERTEST.PLA TXT
cat samplesrc/mousetest.pla | java -jar ac.jar -ptx $PO_IMAGE bld/samples/MOUSETEST.PLA TXT
cat samplesrc/memtest.pla   | java -jar ac.jar -ptx $PO_IMAGE bld/samples/MEMTEST.PLA TXT
cat samplesrc/rod.pla       | java -jar ac.jar -ptx $PO_IMAGE bld/samples/ROD.PLA TXT
cat samplesrc/sieve.pla     | java -jar ac.jar -ptx $PO_IMAGE bld/samples/SIEVE.PLA TXT
cat samplesrc/test.pla      | java -jar ac.jar -ptx $PO_IMAGE bld/samples/TEST.PLA TXT
cat samplesrc/testlib.pla   | java -jar ac.jar -ptx $PO_IMAGE bld/samples/TESTLIB.PLA TXT
cat samplesrc/playseq.pla   | java -jar ac.jar -ptx $PO_IMAGE bld/samples/PLAYSEQ.PLA TXT
cat samplesrc/rpncalc.pla   | java -jar ac.jar -ptx $PO_IMAGE bld/samples/RPNCALC.PLA TXT
cat samplesrc/fatcat.pla    | java -jar ac.jar -ptx $PO_IMAGE bld/samples/FATCAT.PLA TXT
#cat samplesrc/gfxdemo.pla   | java -jar ac.jar -ptx $PO_IMAGE bld/samples/GFXDEMO.PLA TXT
#cat samplesrc/lz4cat.pla    | java -jar ac.jar -ptx $PO_IMAGE bld/samples/LZ4CAT.PLA TXT
cat samplesrc/sfm.pla       | java -jar ac.jar -ptx $PO_IMAGE bld/samples/SFM.PLA TXT
cat samplesrc/sfmsprt.pla   | java -jar ac.jar -ptx $PO_IMAGE bld/samples/SFMSPRT.PLA TXT
cat samplesrc/fppow.pla     | java -jar ac.jar -ptx $PO_IMAGE bld/samples/FPPOW.PLA TXT
cat utilsrc/apple/mon.pla   | java -jar ac.jar -ptx $PO_IMAGE bld/samples/MON.PLA TXT
cat utilsrc/apple/zipchip.pla | java -jar ac.jar -ptx $PO_IMAGE bld/samples/ZIPCHIP.PLA TXT

#mkdir bld/scripts
cat scripts/rod.4th       | java -jar ac.jar -ptx $PO_IMAGE bld/scripts/ROD.4TH TXT
cat scripts/bounce.4th    | java -jar ac.jar -ptx $PO_IMAGE bld/scripts/BOUNCE.4TH TXT
cat scripts/dbounce.4th   | java -jar ac.jar -ptx $PO_IMAGE bld/scripts/DBOUNCE.4TH TXT
cat scripts/hrbounce.4th  | java -jar ac.jar -ptx $PO_IMAGE bld/scripts/HRBOUNCE.4TH TXT
cat scripts/plot.4th      | java -jar ac.jar -ptx $PO_IMAGE bld/scripts/PLOT.4TH TXT
cat scripts/hrplot.4th    | java -jar ac.jar -ptx $PO_IMAGE bld/scripts/HRPLOT.4TH TXT

#mkdir bld/examples
#cat samplesrc/examples/ex.1.pla  bld/examples/EX.1.PLA TXT
#cat samplesrc/examples/ex.2.pla  bld/examples/EX.2.PLA TXT
#cat samplesrc/examples/ex.3.pla  bld/examples/EX.3.PLA TXT
#cat samplesrc/examples/ex.4.pla  bld/examples/EX.4.PLA TXT
#cat samplesrc/examples/ex.5.pla  bld/examples/EX.5.PLA TXT
#cat samplesrc/examples/ex.6.pla  bld/examples/EX.6.PLA TXT
#cat samplesrc/examples/ex.7.pla  bld/examples/EX.7.PLA TXT
#cat samplesrc/examples/ex.8.pla  bld/examples/EX.8.PLA TXT
#cat samplesrc/examples/ex.9.pla  bld/examples/EX.9.PLA TXT
#cat samplesrc/examples/ex.10.pla bld/examples/EX.10.PLA TXT
#cat samplesrc/examples/ex.11.pla bld/examples/EX.11.PLA TXT
#cat samplesrc/examples/ex.12.pla bld/examples/EX.12.PLA TXT
#cat samplesrc/examples/ex.13.pla bld/examples/EX.13.PLA TXT
#cat samplesrc/examples/ex.14.pla bld/examples/EX.14.PLA TXT
#cat samplesrc/examples/ex.15.pla bld/examples/EX.15.PLA TXT
#cat samplesrc/examples/ex.16.pla bld/examples/EX.16.PLA TXT
#cat samplesrc/examples/ex.17.pla bld/examples/EX.17.PLA TXT

#mkdir bld/inc
cat inc/args.plh           | java -jar ac.jar -ptx $PO_IMAGE bld/inc/ARGS.PLH TXT
cat inc/matchfiles.plh     | java -jar ac.jar -ptx $PO_IMAGE bld/inc/MATCHFILES.PLH TXT
cat inc/cmdsys.plh         | java -jar ac.jar -ptx $PO_IMAGE bld/inc/CMDSYS.PLH TXT
cat inc/conio.plh          | java -jar ac.jar -ptx $PO_IMAGE bld/inc/CONIO.PLH TXT
cat inc/lines.plh          | java -jar ac.jar -ptx $PO_IMAGE bld/inc/LINES.PLH TXT
cat inc/hgrfont.plh        | java -jar ac.jar -ptx $PO_IMAGE bld/inc/HGRFONT.PLH TXT
cat inc/hgrtile.plh        | java -jar ac.jar -ptx $PO_IMAGE bld/inc/HGRTILE.PLH TXT
cat inc/hgrsprite.plh      | java -jar ac.jar -ptx $PO_IMAGE bld/inc/HGRSPRITE.PLH TXT
cat inc/hgrlib.plh         | java -jar ac.jar -ptx $PO_IMAGE bld/inc/HGRLIB.PLH TXT
cat inc/grlib.plh          | java -jar ac.jar -ptx $PO_IMAGE bld/inc/GRLIB.PLH TXT
cat inc/dgrlib.plh         | java -jar ac.jar -ptx $PO_IMAGE bld/inc/DGRLIB.PLH TXT
cat inc/fiber.plh          | java -jar ac.jar -ptx $PO_IMAGE bld/inc/FIBER.PLH TXT
cat inc/fileio.plh         | java -jar ac.jar -ptx $PO_IMAGE bld/inc/FILEIO.PLH TXT
cat inc/int32.plh          | java -jar ac.jar -ptx $PO_IMAGE bld/inc/INT32.PLH TXT
cat inc/fpstr.plh          | java -jar ac.jar -ptx $PO_IMAGE bld/inc/FPSTR.PLH TXT
cat inc/fpu.plh            | java -jar ac.jar -ptx $PO_IMAGE bld/inc/FPU.PLH TXT
cat inc/mouse.plh          | java -jar ac.jar -ptx $PO_IMAGE bld/inc/MOUSE.PLH TXT
cat inc/inet.plh           | java -jar ac.jar -ptx $PO_IMAGE bld/inc/INET.PLH TXT
cat inc/longjmp.plh        | java -jar ac.jar -ptx $PO_IMAGE bld/inc/LONGJMP.PLH TXT
cat inc/memmgr.plh         | java -jar ac.jar -ptx $PO_IMAGE bld/inc/MEMMGR.PLH TXT
cat inc/sane.plh           | java -jar ac.jar -ptx $PO_IMAGE bld/inc/SANE.PLH TXT
cat inc/joybuzz.plh        | java -jar ac.jar -ptx $PO_IMAGE bld/inc/JOYBUZZ.PLH TXT
cat inc/portio.plh         | java -jar ac.jar -ptx $PO_IMAGE bld/inc/PORTIO.PLH TXT
cat inc/sdfat.plh          | java -jar ac.jar -ptx $PO_IMAGE bld/inc/SDFAT.PLH TXT
cat inc/sndseq.plh         | java -jar ac.jar -ptx $PO_IMAGE bld/inc/SNDSEQ.PLH TXT
cat inc/spiport.plh        | java -jar ac.jar -ptx $PO_IMAGE bld/inc/SPIPORT.PLH TXT
cat inc/testlib.plh        | java -jar ac.jar -ptx $PO_IMAGE bld/inc/TESTLIB.PLH TXT
cat inc/grafix.plh         | java -jar ac.jar -ptx $PO_IMAGE bld/inc/GRAFIX.PLH TXT
cat inc/lz4.plh            | java -jar ac.jar -ptx $PO_IMAGE bld/inc/LZ4.PLH TXT
cat vmsrc/apple/plvmzp.inc | java -jar ac.jar -ptx $PO_IMAGE bld/inc/PLVMZP.INC TXT

cat dhgr.tk/libs/DHGRLIB.REL     | java -jar ac.jar -p $PO_IMAGE sys/DHGRLIB REL
cat dhgr.tk/libs/DHGRUTILS.REL   | java -jar ac.jar -p $PO_IMAGE sys/DHGRUTILS REL
cat dhgr.tk/inc/dhgrlib.plh      | java -jar ac.jar -ptx $PO_IMAGE bld/inc/DHGRLIB.PLH TXT
cat dhgr.tk/inc/dhgrutils.plh    | java -jar ac.jar -ptx $PO_IMAGE bld/inc/DHGRUTILS.PLH TXT
cat dhgr.tk/test/DHGRTEST.REL    | java -jar ac.jar -p $PO_IMAGE bld/dhgr/DHGRTEST REL
cat dhgr.tk/test/dhgrtest.pla    | java -jar ac.jar -ptx $PO_IMAGE bld/dhgr/DHGRTEST.PLA TXT
cat dhgr.tk/test/ENT.DL.SPR.BIN  | java -jar ac.jar -p $PO_IMAGE bld/dhgr/ENT.DL.SPR BIN
cat dhgr.tk/test/ENT.DN.SPR.BIN  | java -jar ac.jar -p $PO_IMAGE bld/dhgr/ENT.DN.SPR BIN
cat dhgr.tk/test/ENT.DR.SPR.BIN  | java -jar ac.jar -p $PO_IMAGE bld/dhgr/ENT.DR.SPR BIN
cat dhgr.tk/test/ENT.LT.SPR.BIN  | java -jar ac.jar -p $PO_IMAGE bld/dhgr/ENT.LT.SPR BIN
cat dhgr.tk/test/ENT.RT.SPR.BIN  | java -jar ac.jar -p $PO_IMAGE bld/dhgr/ENT.RT.SPR BIN
cat dhgr.tk/test/ENT.UL.SPR.BIN  | java -jar ac.jar -p $PO_IMAGE bld/dhgr/ENT.UL.SPR BIN
cat dhgr.tk/test/ENT.UP.SPR.BIN  | java -jar ac.jar -p $PO_IMAGE bld/dhgr/ENT.UP.SPR BIN
cat dhgr.tk/test/ENT.UR.SPR.BIN  | java -jar ac.jar -p $PO_IMAGE bld/dhgr/ENT.UR.SPR BIN
cat dhgr.tk/test/SPLASH.DHGR.BIN | java -jar ac.jar -p $PO_IMAGE bld/dhgr/SPLASH.DHGR BIN
cat dhgr.tk/utils/dhgrrgb.pla    | java -jar ac.jar -ptx $PO_IMAGE bld/dhgr/DHGRRGB.PLA TXT
cat dhgr.tk/utils/dhgrshow.pla   | java -jar ac.jar -ptx $PO_IMAGE bld/dhgr/DHGRSHOW.PLA TXT
cat dhgr.tk/utils/DHGRRGB.REL    | java -jar ac.jar -p $PO_IMAGE dhgr.tk/utils/DHGRRGB REL
cat dhgr.tk/utils/DHGRSHOW.REL   | java -jar ac.jar -p $PO_IMAGE dhgr.tk/utils/DHGRSHOW REL
cat dhgr.tk/utils/DHGRSPRED.REL  | java -jar ac.jar -p $PO_IMAGE dhgr.tk/utils/DHGRSPRED REL
cat dhgr.tk/utils/DHGREASY.REL   | java -jar ac.jar -p $PO_IMAGE dhgr.tk/utils/DHGREASY REL
cat dhgr.tk/utils/DLGRCONV.REL   | java -jar ac.jar -p $PO_IMAGE dhgr.tk/utils/DLGRCONV REL
cat dhgr.tk/utils/samples/WOZ.RGB.BIN     | java -jar ac.jar -p $PO_IMAGE dhgr.tk/utils/samples/WOZ.RGB BIN
cat dhgr.tk/utils/samples/WOZJOBS.RGB.BIN | java -jar ac.jar -p $PO_IMAGE dhgr.tk/utils/samples/WOZJOBS.RGB BIN
cat dhgr.tk/utils/samples/racecar.pnm     | java -jar ac.jar -p $PO_IMAGE dhgr.tk/utils/samples/RACECAR.PNM BIN
