#!/bin/bash
PO_IMAGE=PLASMA-2.20-BLD.po
cp ../sysfiles/BLANK140.po $PO_IMAGE
./ac.jar -n $PO_IMAGE PLASMA.BLD
cat rel/PLASM#FE1000       | ./ac.jar -p   $PO_IMAGE bld/PLASM REL
cat rel/CODEOPT#FE1000     | ./ac.jar -p   $PO_IMAGE bld/CODEOPT REL
cat inc/args.plh           | ./ac.jar -ptx $PO_IMAGE bld/inc/ARGS.PLH TXT
cat inc/matchfiles.plh     | ./ac.jar -ptx $PO_IMAGE bld/inc/MATCHFILES.PLH TXT
cat inc/cmdsys.plh         | ./ac.jar -ptx $PO_IMAGE bld/inc/CMDSYS.PLH TXT
cat inc/conio.plh          | ./ac.jar -ptx $PO_IMAGE bld/inc/CONIO.PLH TXT
cat inc/lines.plh          | ./ac.jar -ptx $PO_IMAGE bld/inc/LINES.PLH TXT
cat inc/hgrfont.plh        | ./ac.jar -ptx $PO_IMAGE bld/inc/HGRFONT.PLH TXT
cat inc/hgrtile.plh        | ./ac.jar -ptx $PO_IMAGE bld/inc/HGRTILE.PLH TXT
cat inc/hgrsprite.plh      | ./ac.jar -ptx $PO_IMAGE bld/inc/HGRSPRITE.PLH TXT
cat inc/hgrlib.plh         | ./ac.jar -ptx $PO_IMAGE bld/inc/HGRLIB.PLH TXT
cat inc/grlib.plh          | ./ac.jar -ptx $PO_IMAGE bld/inc/GRLIB.PLH TXT
cat inc/dgrlib.plh         | ./ac.jar -ptx $PO_IMAGE bld/inc/DGRLIB.PLH TXT
cat inc/fiber.plh          | ./ac.jar -ptx $PO_IMAGE bld/inc/FIBER.PLH TXT
cat inc/fileio.plh         | ./ac.jar -ptx $PO_IMAGE bld/inc/FILEIO.PLH TXT
cat inc/int32.plh          | ./ac.jar -ptx $PO_IMAGE bld/inc/INT32.PLH TXT
cat inc/fpstr.plh          | ./ac.jar -ptx $PO_IMAGE bld/inc/FPSTR.PLH TXT
cat inc/fpu.plh            | ./ac.jar -ptx $PO_IMAGE bld/inc/FPU.PLH TXT
cat inc/mouse.plh          | ./ac.jar -ptx $PO_IMAGE bld/inc/MOUSE.PLH TXT
cat inc/inet.plh           | ./ac.jar -ptx $PO_IMAGE bld/inc/INET.PLH TXT
cat inc/longjmp.plh        | ./ac.jar -ptx $PO_IMAGE bld/inc/LONGJMP.PLH TXT
cat inc/memmgr.plh         | ./ac.jar -ptx $PO_IMAGE bld/inc/MEMMGR.PLH TXT
cat inc/sane.plh           | ./ac.jar -ptx $PO_IMAGE bld/inc/SANE.PLH TXT
cat inc/joybuzz.plh        | ./ac.jar -ptx $PO_IMAGE bld/inc/JOYBUZZ.PLH TXT
cat inc/portio.plh         | ./ac.jar -ptx $PO_IMAGE bld/inc/PORTIO.PLH TXT
cat inc/sdfat.plh          | ./ac.jar -ptx $PO_IMAGE bld/inc/SDFAT.PLH TXT
cat inc/sndseq.plh         | ./ac.jar -ptx $PO_IMAGE bld/inc/SNDSEQ.PLH TXT
cat inc/spiport.plh        | ./ac.jar -ptx $PO_IMAGE bld/inc/SPIPORT.PLH TXT
cat inc/testlib.plh        | ./ac.jar -ptx $PO_IMAGE bld/inc/TESTLIB.PLH TXT
#cat inc/grafix.plh         | ./ac.jar -ptx $PO_IMAGE bld/inc/GRAFIX.PLH TXT
cat inc/lz4.plh            | ./ac.jar -ptx $PO_IMAGE bld/inc/LZ4.PLH TXT
cat vmsrc/apple/plvmzp.inc | ./ac.jar -ptx $PO_IMAGE bld/inc/PLVMZP.INC TXT

cat samplesrc/hello.pla     | ./ac.jar -ptx $PO_IMAGE bld/samples/HELLO.PLA TXT
cat samplesrc/int32test.pla | ./ac.jar -ptx $PO_IMAGE bld/samples/INT32TEST.PLA TXT
cat samplesrc/coniotest.pla | ./ac.jar -ptx $PO_IMAGE bld/samples/CONIOTEST.PLA TXT
cat samplesrc/grtest.pla    | ./ac.jar -ptx $PO_IMAGE bld/samples/GRTEST.PLA TXT
cat samplesrc/dgrtest.pla   | ./ac.jar -ptx $PO_IMAGE bld/samples/DGRTEST.PLA TXT
cat samplesrc/hgrtest.pla   | ./ac.jar -ptx $PO_IMAGE bld/samples/HGRTEST.PLA TXT
cat samplesrc/tiletest.pla  | ./ac.jar -ptx $PO_IMAGE bld/samples/TILETEST.PLA TXT
cat samplesrc/fibertest.pla | ./ac.jar -ptx $PO_IMAGE bld/samples/FIBERTEST.PLA TXT
cat samplesrc/mousetest.pla | ./ac.jar -ptx $PO_IMAGE bld/samples/MOUSETEST.PLA TXT
cat samplesrc/memtest.pla   | ./ac.jar -ptx $PO_IMAGE bld/samples/MEMTEST.PLA TXT
cat samplesrc/rod.pla       | ./ac.jar -ptx $PO_IMAGE bld/samples/ROD.PLA TXT
#cat samplesrc/sieve.pla    | ./ac.jar -ptx $PO_IMAGE bld/samples/SIEVE.PLA TXT
#cat samplesrc/test.pla     | ./ac.jar -ptx $PO_IMAGE bld/samples/TEST.PLA TXT
#cat samplesrc/testlib.pla  | ./ac.jar -ptx $PO_IMAGE bld/samples/TESTLIB.PLA TXT
cat samplesrc/playseq.pla   | ./ac.jar -ptx $PO_IMAGE bld/samples/PLAYSEQ.PLA TXT
cat samplesrc/rpncalc.pla   | ./ac.jar -ptx $PO_IMAGE bld/samples/RPNCALC.PLA TXT
#cat samplesrc/fatcat.pla   | ./ac.jar -ptx $PO_IMAGE bld/samples/FATCAT.PLA TXT
#cat samplesrc/gfxdemo.pla   | ./ac.jar -ptx $PO_IMAGE bld/samples/GFXDEMO.PLA TXT
cat samplesrc/sfm.pla       | ./ac.jar -ptx $PO_IMAGE bld/samples/SFM.PLA TXT
cat samplesrc/sfmsprt.pla   | ./ac.jar -ptx $PO_IMAGE bld/samples/SFMSPRT.PLA TXT
#cat samplesrc/fppow.pla     | ./ac.jar -ptx $PO_IMAGE bld/samples/FPPOW.PLA TXT
cat utilsrc/apple/mon.pla   | ./ac.jar -ptx $PO_IMAGE bld/samples/MON.PLA TXT
#cat utilsrc/apple/zipchip.pla | ./ac.jar -ptx $PO_IMAGE bld/samples/ZIPCHIP.PLA TXT

cat scripts/rod.4th         | ./ac.jar -ptx $PO_IMAGE bld/scripts/ROD.4TH TXT
cat scripts/bounce.4th      | ./ac.jar -ptx $PO_IMAGE bld/scripts/BOUNCE.4TH TXT
cat scripts/dbounce.4th     | ./ac.jar -ptx $PO_IMAGE bld/scripts/DBOUNCE.4TH TXT
cat scripts/hrbounce.4th    | ./ac.jar -ptx $PO_IMAGE bld/scripts/HRBOUNCE.4TH TXT
cat scripts/plot.4th        | ./ac.jar -ptx $PO_IMAGE bld/scripts/PLOT.4TH TXT
cat scripts/hrplot.4th      | ./ac.jar -ptx $PO_IMAGE bld/scripts/HRPLOT.4TH TXT
