#!/bin/bash
PO_IMAGE=PLASMA-2.20-DEMOS.po
cp ../sysfiles/BLANK140.po $PO_IMAGE
./ac.jar -n $PO_IMAGE PLASMA.DEMOS
cat rel/INT32TEST#FE1000         | ./ac.jar -p   $PO_IMAGE demos/INT32TEST REL
cat rel/apple/CONIOTEST#FE1000   | ./ac.jar -p   $PO_IMAGE demos/CONIOTEST REL
cat rel/apple/ROD#FE1000         | ./ac.jar -p   $PO_IMAGE demos/ROD REL
cat rel/RPNCALC#FE1000           | ./ac.jar -p   $PO_IMAGE demos/RPNCALC REL
cat ../doc/ROGUE.LZ4.BIN         | ./ac.jar -p   $PO_IMAGE demos/ROGUE.LZ4 BIN
cat rel/PRIMEGAP#FE1000          | ./ac.jar -p   $PO_IMAGE demos/PRIMEGAP REL
cat rel/ROGUE#FE1000             | ./ac.jar -p   $PO_IMAGE demos/rogue/ROGUE REL
cat rel/ROGUECOMBAT#FE1000       | ./ac.jar -p   $PO_IMAGE demos/rogue/ROGUECOMBAT REL
cat rel/ROGUEMAP#FE1000          | ./ac.jar -p   $PO_IMAGE demos/rogue/ROGUEMAP REL
cat samplesrc/LEVEL0#040000      | ./ac.jar -ptx $PO_IMAGE demos/rogue/LEVEL0 TXT
cat samplesrc/LEVEL1#040000      | ./ac.jar -ptx $PO_IMAGE demos/rogue/LEVEL1 TXT
cat rel/apple/PLAYSEQ#FE1000     | ./ac.jar -p   $PO_IMAGE demos/music/PLAYSEQ REL
cat mockingboard/ultima3.seq     | ./ac.jar -p   $PO_IMAGE demos/music/ULTIMA3.SEQ BIN
cat mockingboard/startrek.seq    | ./ac.jar -p   $PO_IMAGE demos/music/STARTREK.SEQ BIN
cat rel/HTTPD#FE1000             | ./ac.jar -p   $PO_IMAGE demos/net/HTTPD REL
cat samplesrc/index.html         | ./ac.jar -ptx $PO_IMAGE demos/net/INDEX.HTML TXT
cat rel/apple/TILETEST#FE1000    | ./ac.jar -p   $PO_IMAGE demos/apple2/TILETEST REL
cat rel/apple/HGRTEST#FE1000     | ./ac.jar -p   $PO_IMAGE demos/apple2/HGRTEST REL
cat rel/apple/GRTEST#FE1000      | ./ac.jar -p   $PO_IMAGE demos/apple2/GRTEST REL
cat rel/apple/DGRTEST#FE1000     | ./ac.jar -p   $PO_IMAGE demos/apple2/DGRTEST REL
cat rel/apple/SFM#FE1000         | ./ac.jar -p   $PO_IMAGE demos/apple2/spiders/SFM REL
cat rel/apple/SFMSPRT#FE1000     | ./ac.jar -p   $PO_IMAGE demos/apple2/spiders/SFMSPRT REL
cat rel/apple/SPIPORT#FE1000     | ./ac.jar -p   $PO_IMAGE demos/apple2/sdutils/SPIPORT REL
cat rel/apple/SDFAT#FE1000       | ./ac.jar -p   $PO_IMAGE demos/apple2/sdutils/SDFAT REL
cat rel/apple/FATCAT#FE1000      | ./ac.jar -p   $PO_IMAGE demos/apple2/sdutils/FATCAT REL
cat rel/apple/FATGET#FE1000      | ./ac.jar -p   $PO_IMAGE demos/apple2/sdutils/FATGET REL
cat rel/apple/FATPUT#FE1000      | ./ac.jar -p   $PO_IMAGE demos/apple2/sdutils/FATPUT REL
cat rel/apple/FATREADDSK#FE1000  | ./ac.jar -p   $PO_IMAGE demos/apple2/sdutils/FATREADDSK REL
cat rel/apple/FATWRITEDSK#FE1000 | ./ac.jar -p   $PO_IMAGE demos/apple2/sdutils/FATWRITEDSK REL
