#!/bin/bash
PO_IMAGE=PLASMA-2.20-FPSOS.po
cp ../sysfiles/BLANK140.po $PO_IMAGE
./ac.jar -n $PO_IMAGE PLASMA.FPSOS
cat ../sysfiles/SOS.KERNEL#0C0000  | ./ac.jar -p   $PO_IMAGE SOS.KERNEL \$0C
cat ../sysfiles/SOS.DRIVER#0C0000  | ./ac.jar -p   $PO_IMAGE SOS.DRIVER \$0C
cat rel/apple/SOS.INTERP#050000    | ./ac.jar -p   $PO_IMAGE SOS.INTERP \$05
cat rel/apple/SOS.CMD#FE1000       | ./ac.jar -p   $PO_IMAGE SOS.CMD REL
cat rel/apple/SOS.INTERPJIT#050000 | ./ac.jar -p   $PO_IMAGE SOS.INTERPJIT \$05
cat rel/apple/SOS.CMDJIT#FE1000    | ./ac.jar -p   $PO_IMAGE SOS.CMDJIT REL
cat rel/apple/SOS#FE1000           | ./ac.jar -p   $PO_IMAGE sys/SOS REL
cat rel/apple/GRAFIX#FE1000        | ./ac.jar -p   $PO_IMAGE sys/GRAFIX REL
cat rel/FPSTR#FE1000               | ./ac.jar -p   $PO_IMAGE sys/FPSTR REL
cat rel/FPU#FE1000                 | ./ac.jar -p   $PO_IMAGE sys/FPU REL
cat rel/SANE#FE1000                | ./ac.jar -p   $PO_IMAGE sys/SANE REL
cat ../sysfiles/FP6502.CODE#060000 | ./ac.jar -p   $PO_IMAGE sys/FP6502.CODE BIN
cat ../sysfiles/ELEMS.CODE#060000  | ./ac.jar -p   $PO_IMAGE sys/ELEMS.CODE BIN
cat inc/grafix.plh                 | ./ac.jar -ptx $PO_IMAGE bld/inc/GRAFIX.PLH TXT
cat samplesrc/gfxdemo.pla          | ./ac.jar -ptx $PO_IMAGE bld/samples/GFXDEMO.PLA TXT
cat scripts/grafix.4th             | ./ac.jar -ptx $PO_IMAGE sys/scripts/GRAFIX.4TH TXT
cat scripts/gfxplot.4th            | ./ac.jar -ptx $PO_IMAGE bld/scripts/GFXPLOT.4TH TXT
cat rel/apple/GFXDEMO#FE1000       | ./ac.jar -p   $PO_IMAGE demos/apple3/GFXDEMO REL
cat samplesrc/APPLE3.PIX#060000    | ./ac.jar -p   $PO_IMAGE demos/apple3/APPLE3.PIX BIN
