#!/bin/bash
PO_IMAGE=PLASMA-2.20-INET.po
cp ../sysfiles/BLANK140.po $PO_IMAGE
java -jar ac.jar -n $PO_IMAGE PLASMA.INET
cat rel/INET#FE1000                | java -jar ac.jar -p   $PO_IMAGE sys/INET REL
cat rel/DHCP#FE1000                | java -jar ac.jar -p   $PO_IMAGE sys/DHCP REL
cat rel/ETHERIP#FE1000             | java -jar ac.jar -p   $PO_IMAGE sys/ETHERIP REL
cat rel/apple/UTHERNET2#FE1000     | java -jar ac.jar -p   $PO_IMAGE sys/UTHERNET2 REL
cat rel/apple/UTHERNET#FE1000      | java -jar ac.jar -p   $PO_IMAGE sys/UTHERNET REL
cat rel/TFTPD#FE1000               | java -jar ac.jar -p   $PO_IMAGE sys/TFTPD REL
