#!/bin/bash
PO_IMAGE=PLASMA-2.20-INST.po
cp ../sysfiles/BLANK140.po $PO_IMAGE
java -jar ac.jar -n $PO_IMAGE PLASMA.INST
cat ../sysfiles/PRODOS#FF0000      | java -jar ac.jar -p   $PO_IMAGE PRODOS SYS
cat rel/apple/CMD#061000           | java -jar ac.jar -p   $PO_IMAGE CMD BIN $1000
cat rel/apple/CMD.128#061000       | java -jar ac.jar -p   $PO_IMAGE CMD.128 BIN $1000
cat rel/apple/PLASMA.SYSTEM#FF2000 | java -jar ac.jar -p   $PO_IMAGE PLASMA.SYSTEM SYS
cat rel/apple/PLVM.128#FF2000      | java -jar ac.jar -p   $PO_IMAGE PLVM.128 SYS
cat rel/apple/PLVM16#FF2000        | java -jar ac.jar -p   $PO_IMAGE PLVM16 SYS
cat rel/apple/JIT#FE1000           | java -jar ac.jar -p   $PO_IMAGE sys/JIT REL
cat rel/apple/JIT16#FE1000         | java -jar ac.jar -p   $PO_IMAGE sys/JIT16 REL
cat rel/apple/FILEIO#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/FILEIO REL
cat rel/apple/CONIO#FE1000         | java -jar ac.jar -p   $PO_IMAGE sys/CONIO REL
cat rel/apple/COPY#FE1000          | java -jar ac.jar -p   $PO_IMAGE sys/COPY REL
cat rel/apple/DEL#FE1000           | java -jar ac.jar -p   $PO_IMAGE sys/DEL REL
cat rel/apple/REN#FE1000           | java -jar ac.jar -p   $PO_IMAGE sys/REN REL
cat rel/apple/CAT#FE1000           | java -jar ac.jar -p   $PO_IMAGE sys/CAT REL
cat rel/apple/TYPE#FE1000          | java -jar ac.jar -p   $PO_IMAGE sys/TYPE REL
cat rel/apple/NEWDIR#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/NEWDIR REL
cat rel/apple/MATCHFILES#FE1000    | java -jar ac.jar -p   $PO_IMAGE sys/MATCHFILES REL
cat rel/ARGS#FE1000                | java -jar ac.jar -p   $PO_IMAGE sys/ARGS REL
cat rel/LONGJMP#FE1000             | java -jar ac.jar -p   $PO_IMAGE sys/LONGJMP REL
cat rel/INT32#FE1000               | java -jar ac.jar -p   $PO_IMAGE sys/INT32 REL
cat rel/HRFORTH#FE1000             | java -jar ac.jar -p   $PO_IMAGE sys/HRFORTH REL
cat rel/HR2FORTH#FE1000            | java -jar ac.jar -p   $PO_IMAGE sys/HR2FORTH REL
cat rel/TX2FORTH#FE1000            | java -jar ac.jar -p   $PO_IMAGE sys/TX2FORTH REL
cat rel/PLFORTH#FE1000             | java -jar ac.jar -p   $PO_IMAGE sys/PLFORTH REL
cat scripts/plasma.4th             | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/PLASMA.4TH TXT
cat scripts/machid.4th             | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/MACHID.4TH TXT
cat scripts/conio.4th              | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/CONIO.4TH TXT
cat scripts/fileio.4th             | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/FILEIO.4TH TXT
cat scripts/grlib.4th              | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/GRLIB.4TH TXT
cat scripts/dgrlib.4th             | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/DGRLIB.4TH TXT
cat scripts/hgrlib.4th             | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/HGRLIB.4TH TXT
cat scripts/int32.4th              | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/INT32.4TH TXT
cat scripts/fpu.4th                | java -jar ac.jar -ptx $PO_IMAGE sys/scripts/FPU.4TH TXT
cat scripts/hdinstall1.4th         | java -jar ac.jar -ptx $PO_IMAGE HDINSTALL.4TH TXT
cat scripts/hdinstall2.4th         | java -jar ac.jar -ptx $PO_IMAGE HDINSTALL2.4TH TXT
echo "+PLFORTH HDINSTALL.4TH"      | java -jar ac.jar -ptx $PO_IMAGE AUTORUN TXT
