#!/bin/bash
PO_IMAGE=DRAWL.po
cp ../sysfiles/BLANK140.po $PO_IMAGE
./ac.jar -n $PO_IMAGE PLASMA.LISP
cat ../sysfiles/PRODOS#FF0000      | ./ac.jar -p   $PO_IMAGE PRODOS SYS
cat rel/apple/CMD#061000           | ./ac.jar -p   $PO_IMAGE CMD BIN $1000
cat rel/apple/CMD.128#061000       | ./ac.jar -p   $PO_IMAGE CMD.128 BIN $1000
cat rel/apple/PLASMA.SYSTEM#FF2000 | ./ac.jar -p   $PO_IMAGE PLASMA.SYSTEM SYS
cat rel/apple/PLVM.128#FF2000      | ./ac.jar -p   $PO_IMAGE PLVM.128 SYS
cat rel/apple/PLVM16#FF2000        | ./ac.jar -p   $PO_IMAGE PLVM16 SYS
cat rel/apple/JIT#FE1000           | ./ac.jar -p   $PO_IMAGE sys/JIT REL
cat rel/apple/JIT16#FE1000         | ./ac.jar -p   $PO_IMAGE sys/JIT16 REL
cat rel/apple/FILEIO#FE1000        | ./ac.jar -p   $PO_IMAGE sys/FILEIO REL
cat rel/apple/CONIO#FE1000         | ./ac.jar -p   $PO_IMAGE sys/CONIO REL
cat rel/ARGS#FE1000                | ./ac.jar -p   $PO_IMAGE sys/ARGS REL
cat rel/LONGJMP#FE1000             | ./ac.jar -p   $PO_IMAGE sys/LONGJMP REL
cat rel/INT32#FE1000               | ./ac.jar -p   $PO_IMAGE sys/INT32 REL
cat rel/FPSTR#FE1000               | ./ac.jar -p   $PO_IMAGE sys/FPSTR REL
cat rel/SANE#FE1000                | ./ac.jar -p   $PO_IMAGE sys/SANE REL
cat ../sysfiles/FP6502.CODE#060000 | ./ac.jar -p   $PO_IMAGE sys/FP6502.CODE BIN
cat ../sysfiles/ELEMS.CODE#060000  | ./ac.jar -p   $PO_IMAGE sys/ELEMS.CODE BIN
cat rel/ED#FE1000                 | ./ac.jar -p   $PO_IMAGE sys/ED REL
cat rel/SEXPR#FE1000               | ./ac.jar -p   $PO_IMAGE lisp/SEXPR REL
#cat lisp/s-expr.pla                | ./ac.jar -ptx $PO_IMAGE lisp/SEXPR.PLA TXT
cat rel/SMATH#FE1000               | ./ac.jar -p   $PO_IMAGE lisp/SMATH REL
#cat lisp/s-math.pla                | ./ac.jar -ptx $PO_IMAGE lisp/SMATH.PLA TXT
cat rel/DRAWL#FE1000               | ./ac.jar -p   $PO_IMAGE lisp/DRAWL REL
#cat lisp/drawl.pla                 | ./ac.jar -ptx $PO_IMAGE lisp/DRAWL.PLA TXT
cat lisp/set.lisp                  | ./ac.jar -ptx $PO_IMAGE lisp/SET.LISP TXT
cat lisp/list.lisp                 | ./ac.jar -ptx $PO_IMAGE lisp/LIST.LISP TXT
cat lisp/maplist.lisp              | ./ac.jar -ptx $PO_IMAGE lisp/MAPLIST.LISP TXT
cat lisp/gcd.lisp                  | ./ac.jar -ptx $PO_IMAGE lisp/GCD.LISP TXT
cat lisp/fact.lisp                 | ./ac.jar -ptx $PO_IMAGE lisp/FACT.LISP TXT
cat lisp/loop.lisp                 | ./ac.jar -ptx $PO_IMAGE lisp/LOOP.LISP TXT
cat lisp/minmax.lisp               | ./ac.jar -ptx $PO_IMAGE lisp/MINMAX.LISP TXT
cat lisp/prog.lisp                 | ./ac.jar -ptx $PO_IMAGE lisp/PROG.LISP TXT
cat lisp/lores.lisp                | ./ac.jar -ptx $PO_IMAGE lisp/LORES.LISP TXT
cat lisp/defun.lisp                | ./ac.jar -ptx $PO_IMAGE lisp/DEFUN.LISP TXT
cat lisp/rod.lisp                  | ./ac.jar -ptx $PO_IMAGE lisp/ROD.LISP TXT
