#!/bin/bash
PO_IMAGE=PLASMA-2.20-SYS.po
cp ../sysfiles/BLANK140.po $PO_IMAGE
java -jar ac.jar -n $PO_IMAGE PLASMA.SYS
#cat ../sysfiles/PRODOS#FF0000      | java -jar ac.jar -p   $PO_IMAGE PRODOS SYS
#cat rel/apple/CMD#061000           | java -jar ac.jar -p   $PO_IMAGE CMD BIN $1000
#cat rel/apple/CMD.128#061000       | java -jar ac.jar -p   $PO_IMAGE CMD.128 BIN $1000
#cat rel/apple/PLASMA.SYSTEM#FF2000 | java -jar ac.jar -p   $PO_IMAGE PLASMA.SYSTEM SYS
#cat rel/apple/PLVM.128#FF2000      | java -jar ac.jar -p   $PO_IMAGE PLVM.128 SYS
#cat rel/apple/PLVM16#FF2000        | java -jar ac.jar -p   $PO_IMAGE PLVM16 SYS
cat ../doc/Editor.md                | java -jar ac.jar -ptx $PO_IMAGE EDITOR.README TXT
#cat rel/apple/FILEIO#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/FILEIO REL
#cat rel/apple/CONIO#FE1000         | java -jar ac.jar -p   $PO_IMAGE sys/CONIO REL
cat rel/LINES#FE1000                | java -jar ac.jar -p   $PO_IMAGE sys/LINES REL
cat rel/apple/HGRFONT#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/HGRFONT REL
cat rel/apple/HGRTILE#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/HGRTILE REL
cat rel/apple/HGRSPRITE#FE1000      | java -jar ac.jar -p   $PO_IMAGE sys/HGRSPRITE REL
cat rel/apple/HGRLIB#FE1000         | java -jar ac.jar -p   $PO_IMAGE sys/HGRLIB REL
cat rel/apple/GRLIB#FE1000          | java -jar ac.jar -p   $PO_IMAGE sys/GRLIB REL
cat rel/apple/DGRLIB#FE1000         | java -jar ac.jar -p   $PO_IMAGE sys/DGRLIB REL
cat rel/apple/VBLANK#FE1000         | java -jar ac.jar -p   $PO_IMAGE sys/VBLANK REL
#cat rel/apple/COPY#FE1000          | java -jar ac.jar -p   $PO_IMAGE sys/COPY REL
#cat rel/apple/DEL#FE1000           | java -jar ac.jar -p   $PO_IMAGE sys/DEL REL
#cat rel/apple/REN#FE1000           | java -jar ac.jar -p   $PO_IMAGE sys/REN REL
#cat rel/apple/CAT#FE1000           | java -jar ac.jar -p   $PO_IMAGE sys/CAT REL
#cat rel/apple/NEWDIR#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/NEWDIR REL
#cat rel/apple/TYPE#FE1000          | java -jar ac.jar -p   $PO_IMAGE sys/TYPE REL
#cat rel/apple/MATCHFILES#FE1000    | java -jar ac.jar -p   $PO_IMAGE sys/MATCHFILES REL
#cat rel/ARGS#FE1000                | java -jar ac.jar -p   $PO_IMAGE sys/ARGS REL
cat rel/apple/INITSLOT#FE1000       | java -jar ac.jar -p   $PO_IMAGE sys/INITSLOT REL
cat rel/ED#FE1000                   | java -jar ac.jar -p   $PO_IMAGE sys/ED REL
cat rel/FIBER#FE1000                | java -jar ac.jar -p   $PO_IMAGE sys/FIBER REL
#cat rel/LONGJMP#FE1000             | java -jar ac.jar -p   $PO_IMAGE sys/LONGJMP REL
cat rel/MEMMGR#FE1000               | java -jar ac.jar -p   $PO_IMAGE sys/MEMMGR REL
cat rel/apple/MOUSE#FE1000          | java -jar ac.jar -p   $PO_IMAGE sys/MOUSE REL
cat rel/apple/PORTIO#FE1000         | java -jar ac.jar -p   $PO_IMAGE sys/PORTIO REL
cat rel/apple/JOYBUZZ#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/JOYBUZZ REL
cat rel/apple/SNDSEQ#FE1000         | java -jar ac.jar -p   $PO_IMAGE sys/SNDSEQ REL
cat rel/apple/INITSLOT#FE1000       | java -jar ac.jar -p   $PO_IMAGE sys/INITSLOT REL
#cat rel/apple/JIT#FE1000           | java -jar ac.jar -p   $PO_IMAGE sys/JIT REL
#cat rel/apple/JIT16#FE1000         | java -jar ac.jar -p   $PO_IMAGE sys/JIT16 REL
cat rel/apple/JITUNE#FE1000         | java -jar ac.jar -p   $PO_IMAGE sys/JITUNE REL
cat rel/apple/ZIPCHIP#FE1000        | java -jar ac.jar -p   $PO_IMAGE sys/ZIPCHIP REL
cat rel/LZ4#FE1000                  | java -jar ac.jar -p   $PO_IMAGE sys/LZ4 REL
#cat rel/INT32#FE1000               | java -jar ac.jar -p   $PO_IMAGE sys/INT32 REL
