#!/bin/bash


# Build tools
echo "BLD/PLASM";    atftp $1 --put -l rel/PLASM#FE1000 -r $2/BLD/PLASM#FE1000
echo "BLD/CODEOPT";  atftp $1 --put -l rel/CODEOPT#FE1000 -r $2/BLD/CODEOPT#FE1000

#Build incs
echo "INC/ARGS.PLH";     atftp $1 --option "mode netsacii" --put -l src/inc/args.plh -r $2/BLD/INC/ARGS.PLH#040000
echo "INC/CMDSYS.PLH";   atftp $1 --option "mode netsacii" --put -l src/inc/cmdsys.plh -r $2/BLD/INC/CMDSYS.PLH#040000
echo "INC/CONIO.PLH";    atftp $1 --option "mode netsacii" --put -l src/inc/conio.plh -r $2/BLD/INC/CONIO.PLH#040000
echo "INC/DGR.PLH";      atftp $1 --option "mode netsacii" --put -l src/inc/dgr.plh -r $2/BLD/INC/DGR.PLH#040000
echo "INC/FIBER.PLH";    atftp $1 --option "mode netsacii" --put -l src/inc/fiber.plh -r $2/BLD/INC/FIBER.PLH#040000
echo "INC/FILEIO.PLH";   atftp $1 --option "mode netsacii" --put -l src/inc/fileio.plh -r $2/BLD/INC/FILEIO.PLH#040000
echo "INC/FPSTR.PLH";    atftp $1 --option "mode netsacii" --put -l src/inc/fpstr.plh -r $2/BLD/INC/FPSTR.PLH#040000
echo "INC/FPU.PLH";      atftp $1 --option "mode netsacii" --put -l src/inc/fpu.plh -r $2/BLD/INC/FPU.PLH#040000
echo "INC/GRAFIX.PLH";   atftp $1 --option "mode netsacii" --put -l src/inc/grafix.plh -r $2/BLD/INC/GRAFIX.PLH#040000
echo "INC/INET.PLH";     atftp $1 --option "mode netsacii" --put -l src/inc/inet.plh -r $2/BLD/INC/INET.PLH#040000
echo "INC/JOYBUZZ.PLH";  atftp $1 --option "mode netsacii" --put -l src/inc/joybuzz.plh -r $2/BLD/INC/JOYBUZZ.PLH#040000
echo "INC/LONGJUMP.PLH"; atftp $1 --option "mode netsacii" --put -l src/inc/longjmp.plh -r $2/BLD/INC/LONGJUMP.PLH#040000
echo "INC/LZ4.PLH";      atftp $1 --option "mode netsacii" --put -l src/inc/lz4.plh -r $2/BLD/INC/LZ4.PLH#040000
echo "INC/MEMMGR.PLH";   atftp $1 --option "mode netsacii" --put -l src/inc/memmgr.plh -r $2/BLD/INC/MEMMGR.PLH#040000
echo "INC/MOUSE.PLH";    atftp $1 --option "mode netsacii" --put -l src/inc/mouse.plh -r $2/BLD/INC/MOUSE.PLH#040000
echo "INC/PORTIO.PLH";   atftp $1 --option "mode netsacii" --put -l src/inc/portio.plh -r $2/BLD/INC/PORTIO.PLH#040000
echo "INC/SANE.PLH";     atftp $1 --option "mode netsacii" --put -l src/inc/sane.plh -r $2/BLD/INC/SANE.PLH#040000
echo "INC/SDFAT.PLH";    atftp $1 --option "mode netsacii" --put -l src/inc/sdfat.plh -r $2/BLD/INC/SDFAT.PLH#040000
echo "INC/SNDSEQ.PLH";   atftp $1 --option "mode netsacii" --put -l src/inc/sndseq.plh -r $2/BLD/INC/SNDSEQ.PLH#040000
echo "INC/SPIPORT.PLH";  atftp $1 --option "mode netsacii" --put -l src/inc/spiport.plh -r $2/BLD/INC/SPIPORT.PLH#040000
echo "INC/TESTLIB.PLH";  atftp $1 --option "mode netsacii" --put -l src/inc/testlib.plh -r $2/BLD/INC/TESTLIB.PLH#040000

# Sample source
echo "BLD/MOUSETEST.PLA"; atftp $1 --option "mode netsacii" --put -l src/mousetest.pla -r $2/BLD/MOUSETEST.PLA#040000
