#!/bin/bash

# Core utilities
echo "SYS/ED";       atftp $1 --put -l rel/ED#FE1000 -r $2/SYS/ED#FE1000
echo "SYS/COPY";     atftp $1 --put -l rel/COPY#FE1000 -r $2/SYS/COPY#FE1000
echo "SYS/DEL";      atftp $1 --put -l rel/DEL#FE1000 -r $2/SYS/DEL#FE1000
echo "SYS/REN";      atftp $1 --put -l rel/REN#FE1000 -r $2/SYS/REN#FE1000
echo "SYS/CAT";      atftp $1 --put -l rel/CAT#FE1000 -r $2/SYS/CAT#FE1000
echo "SYS/NEWDIR";   atftp $1 --put -l rel/NEWDIR#FE1000 -r $2/SYS/NEWDIR#FE1000
echo "SYS/TYPE";     atftp $1 --put -l rel/TYPE#FE1000 -r $2/SYS/TYPE#FE1000
echo "SYS/TFTPD";    atftp $1 --put -l rel/TFTPD#FE1000 -r $2/SYS/TFTPD#FE1000
echo "SYS/LZ4";      atftp $1 --put -l rel/LZ4#FE1000 -r $2/SYS/LZ4#FE1000
echo "SYS/MON";      atftp $1 --put -l rel/apple/MON#FE1000 -r $2/SYS/MON#FE1000
echo "SYS/SOS";      atftp $1 --put -l rel/apple/SOS#FE1000 -r $2/SYS/SOS#FE1000
