#!/bin/bash

# FORTH and scripts
echo "SYS/PLFORTH"; atftp --option "disable windowsize" $1 --put -l rel/PLFORTH#FE1000 -r $2/SYS/PLFORTH#FE1000
echo "SYS/HRFORTH"; atftp --option "disable windowsize" $1 --put -l rel/HRFORTH#FE1000 -r $2/SYS/HRFORTH#FE1000
echo "SYS/HR2FORTH"; atftp --option "disable windowsize" $1 --put -l rel/HR2FORTH#FE1000 -r $2/SYS/HR2FORTH#FE1000
echo "SCRIPTS/CONIO.4TH";   atftp --option "disable windowsize" $1 --put -l scripts/conio.4th -r $2/SYS/SCRIPTS/CONIO.4TH#040000
echo "SCRIPTS/FILEIO.4TH";  atftp --option "disable windowsize" $1 --put -l scripts/fileio.4th -r $2/SYS/SCRIPTS/FILEIO.4TH#040000
echo "SCRIPTS/FPU.4TH";     atftp --option "disable windowsize" $1 --put -l scripts/fpu.4th -r $2/SYS/SCRIPTS/FPU.4TH#040000
echo "SCRIPTS/GRLIB.4TH";   atftp --option "disable windowsize" $1 --put -l scripts/grlib.4th -r $2/SYS/SCRIPTS/GRLIB.4TH#040000
echo "SCRIPTS/HGRLIB.4TH";  atftp --option "disable windowsize" $1 --put -l scripts/hgrlib.4th -r $2/SYS/SCRIPTS/HGRLIB.4TH#040000
echo "SCRIPTS/INT32.4TH";   atftp --option "disable windowsize" $1 --put -l scripts/int32.4th -r $2/SYS/SCRIPTS/INT32.4TH#040000
echo "SCRIPTS/PLASMA.4TH";  atftp --option "disable windowsize" $1 --put -l scripts/plasma.4th -r $2/SYS/SCRIPTS/PLASMA.4TH#040000

# Sample scripts
echo "SCRIPTS/BOUNCE.4TH";  atftp --option "disable windowsize" $1 --put -l scripts/bounce.4th -r $2/SCRIPTS/BOUNCE.4TH#040000
echo "SCRIPTS/HRBOUNCE.4TH";  atftp --option "disable windowsize" $1 --put -l scripts/hrbounce.4th -r $2/SCRIPTS/HRBOUNCE.4TH#040000
echo "SCRIPTS/ROD.4TH";  atftp --option "disable windowsize" $1 --put -l scripts/rod.4th -r $2/SCRIPTS/ROD.4TH#040000
