#!/bin/bash

# Demos
echo "DEMOS/RPNCALC";             atftp $1 --put -l rel/RPNCALC#FE1000            -r $2/DEMOS/RPNCALC#FE1000
echo "DEMOS/LZ4CAT";              atftp $1 --put -l rel/LZ4CAT#FE1000             -r $2/DEMOS/LZ4CAT#FE1000
echo "DEMOS/SIEVE";               atftp $1 --put -l rel/SIEVE#FE1000              -r $2/DEMOS/SIEVE#FE1000
echo "DEMOS/ROD";                 atftp $1 --put -l rel/apple/ROD#FE1000          -r $2/DEMOS/ROD#FE1000
echo "DEMOS/INT32TEST";           atftp $1 --put -l rel/INT32TEST#FE1000       -r $2/DEMOS/INT32TEST#FE1000

# Music demo
echo "DEMOS/MUSIC/PLAYSEQ";       atftp $1 --put -l rel/apple/PLAYSEQ#FE1000      -r $2/DEMOS/MUSIC/PLAYSEQ#FE1000
                                  atftp $1 --put -l mockingboard/ultima3.seq      -r $2/DEMOS/MUSIC/ULTIMA3.SEQ#060000
                                  atftp $1 --put -l mockingboard/startrek.seq     -r $2/DEMOS/MUSIC/STARTREK.SEQ#060000

# Rogue demo
echo "DEMOS/ROGUE/ROGUE";         atftp $1 --put -l rel/ROGUE#FE1000              -r $2/DEMOS/ROGUE/ROGUE#FE1000
echo "DEMOS/ROGUE/ROGUEMAP";      atftp $1 --put -l rel/ROGUEMAP#FE1000           -r $2/DEMOS/ROGUE/ROGUEMAP#FE1000
echo "DEMOS/ROGUE/ROGUECOMBAT";   atftp $1 --put -l rel/ROGUECOMBAT#FE1000        -r $2/DEMOS/ROGUE/ROGUECOMBAT#FE1000
                                  atftp $1 --put -l samplesrc/LEVEL0#040000       -r $2/DEMOS/ROGUE/LEVEL0#040000
                                  atftp $1 --put -l samplesrc/LEVEL1#040000       -r $2/DEMOS/ROGUE/LEVEL1#040000

# Net demos
echo "DEMOS/NET/HTTPD";           atftp $1 --put -l rel/HTTPD#FE1000              -r $2/DEMOS/NET/HTTPD#FE1000
                                  atftp $1 --put -l samplesrc/index.html          -r $2/DEMOS/NET/INDEX.HTML#040000

# Apple 2 demos
echo "DEMOS/APPLE2/TILETEST";            atftp $1 --put -l rel/apple/TILETEST#FE1000       -r $2/DEMOS/APPLE2/TILETEST#FE1000
echo "DEMOS/APPLE2/HGRTEST";             atftp $1 --put -l rel/apple/HGRTEST#FE1000       -r $2/DEMOS/APPLE2/HGRTEST#FE1000
echo "DEMOS/APPLE2/GRTEST";              atftp $1 --put -l rel/apple/GRTEST#FE1000       -r $2/DEMOS/APPLE2/GRTEST#FE1000
echo "DEMOS/APPLE2/DGRTEST";             atftp $1 --put -l rel/apple/DGRTEST#FE1000      -r $2/DEMOS/APPLE2/DGRTEST#FE1000

# Spiders from Mars
echo "DEMOS/APPLE2/SPIDERS/SFM";         atftp $1 --put -l rel/apple/SFM#FE1000      -r $2/DEMOS/APPLE2/SPIDERS/SFM#FE1000
echo "DEMOS/APPLE2/SPIDERS/SFMSPRT";     atftp $1 --put -l rel/apple/SFMSPRT#FE1000      -r $2/DEMOS/APPLE2/SPIDERS/SFMSPRT#FE1000

# Arduino+SD card demos
echo "DEMOS/APPLE2/SDUTILS/SPIPORT";     atftp $1 --put -l rel/apple/SPIPORT#FE1000      -r $2/DEMOS/APPLE2/SDUTILS/SPIPORT#FE1000
echo "DEMOS/APPLE2/SDUTILS/SDFAT";       atftp $1 --put -l rel/apple/SDFAT#FE1000        -r $2/DEMOS/APPLE2/SDUTILS/SDFAT#FE1000
echo "DEMOS/APPLE2/SDUTILS/FATCAT";      atftp $1 --put -l rel/apple/FATCAT#FE1000       -r $2/DEMOS/APPLE2/SDUTILS/FATCAT#FE1000
echo "DEMOS/APPLE2/SDUTILS/FATGET";      atftp $1 --put -l rel/apple/FATGET#FE1000       -r $2/DEMOS/APPLE2/SDUTILS/FATGET#FE1000
echo "DEMOS/APPLE2/SDUTILS/FATPUT";      atftp $1 --put -l rel/apple/FATPUT#FE1000       -r $2/DEMOS/APPLE2/SDUTILS/FATPUT#FE1000
echo "DEMOS/APPLE2/SDUTILS/FATREADDSK";  atftp $1 --put -l rel/apple/FATREADDSK#FE1000   -r $2/DEMOS/APPLE2/SDUTILS/FATREADDSK#FE1000
echo "DEMOS/APPLE2/SDUTILS/FATWRITEDSK"; atftp $1 --put -l rel/apple/FATWRITEDSK#FE1000  -r $2/DEMOS/APPLE2/SDUTILS/FATWRITEDSK#FE1000

