#!/bin/bash

# Core VM, CMDSYS, JITC files
echo "PLASMA.SYSTEM"; atftp $1 --put -l rel/apple/PLASMA.SYSTEM#FF2000 -r PLASMA.SYSTEM#FF2000
echo "PLVM.128";      atftp $1 --put -l rel/apple/PLVM.128#FF2000 -r PLVM.128#FF2000
echo "PLVM16";        atftp $1 --put -l rel/apple/PLVM16#FF2000 -r PLVM16#FF2000
echo "CMD";           atftp $1 --put -l rel/apple/CMD#061000 -r CMD#061000
echo "CMD128";        atftp $1 --put -l rel/apple/CMD128#061000 -r CMD128#061000
echo "SYS/JIT";       atftp $1 --put -l rel/apple/JIT#FE1000 -r SYS/JIT#FE1000
echo "SYS/JIT16";     atftp $1 --put -l rel/apple/JIT16#FE1000 -r SYS/JIT16#FE1000
echo "SYS/JITUNE";    atftp $1 --put -l rel/apple/JITUNE#FE1000 -r SYS/JITUNE#FE1000

# Core libraries
echo "SYS/ARGS";     atftp $1 --put -l rel/ARGS#FE1000 -r SYS/ARGS#FE1000
echo "SYS/DHCP";     atftp $1 --put -l rel/DHCP#FE1000 -r SYS/DHCP#FE1000
echo "SYS/ED";       atftp $1 --put -l rel/ED#FE1000 -r SYS/ED#FE1000
echo "SYS/ETHERIP";  atftp $1 --put -l rel/ETHERIP#FE1000 -r SYS/ETHERIP#FE1000
echo "SYS/FIBER";    atftp $1 --put -l rel/FIBER#FE1000 -r SYS/FIBER#FE1000
echo "SYS/FPSTR";    atftp $1 --put -l rel/FPSTR#FE1000 -r SYS/FPSTR#FE1000
echo "SYS/FPU";      atftp $1 --put -l rel/FPU#FE1000 -r SYS/FPU#FE1000
echo "SYS/INET";     atftp $1 --put -l rel/INET#FE1000 -r SYS/INET#FE1000
echo "SYS/LONGJUMP"; atftp $1 --put -l rel/LONGJMP#FE1000 -r SYS/LONGJMP#FE1000
echo "SYS/LZ4";      atftp $1 --put -l rel/LZ4#FE1000 -r SYS/LZ4#FE1000
echo "SYS/MEMMGR";   atftp $1 --put -l rel/MEMMGR#FE1000 -r SYS/MEMMGR#FE1000
echo "SYS/SANE";     atftp $1 --put -l rel/SANE#FE1000 -r SYS/SANE#FE1000
echo "SYS/CONIO";    atftp $1 --put -l rel/apple/CONIO#FE1000 -r SYS/CONIO#FE1000
echo "SYS/DGR";      atftp $1 --put -l rel/apple/DGR#FE1000 -r SYS/DGR#FE1000
echo "SYS/FILEIO";   atftp $1 --put -l rel/apple/FILEIO#FE1000 -r SYS/FILEIO#FE1000
echo "SYS/GRAFIX";   atftp $1 --put -l rel/apple/GRAFIX#FE1000 -r SYS/GRAFIX#FE1000
echo "SYS/JOYBUZZ";  atftp $1 --put -l rel/apple/JOYBUZZ#FE1000 -r SYS/JOYBUZZ#FE1000
echo "SYS/MON";      atftp $1 --put -l rel/apple/MON#FE1000 -r SYS/MON#FE1000
echo "SYS/PORTIO";   atftp $1 --put -l rel/apple/PORTIO#FE1000 -r SYS/PORTIO#FE1000
echo "SYS/SPIPORT";  atftp $1 --put -l rel/apple/SPIPORT#FE1000 -r SYS/SPIPORT#FE1000
echo "SYS/UTHERNET2";atftp $1 --put -l rel/apple/UTHERNET2#FE1000 -r SYS/UTHERNET2#FE1000
echo "SYS/UTHERNET"; atftp $1 --put -l rel/apple/UTHERNET#FE1000 -r SYS/UTHERNET#FE1000

# Build tools
echo "BLD/PLASM";    atftp $1 --put -l rel/PLASM#FE1000 -r BLD/PLASM#FE1000
echo "BLD/CODEOPT";  atftp $1 --put -l rel/CODEOPT#FE1000 -r BLD/CODEOPT#FE1000
