#!/bin/bash

# Core VM, CMDSYS, JITC files
echo "PLASMA.SYSTEM"; atftp $1 --put -l rel/apple/PLASMA.SYSTEM#FF2000 -r $2/PLASMA.SYSTEM#FF2000
echo "PLVM.128";      atftp $1 --put -l rel/apple/PLVM.128#FF2000 -r $2/PLVM.128#FF2000
echo "PLVM16";        atftp $1 --put -l rel/apple/PLVM16#FF2000 -r $2/PLVM16#FF2000
echo "CMD";           atftp $1 --put -l rel/apple/CMD#061000 -r $2/CMD#061000
echo "CMD128";        atftp $1 --put -l rel/apple/CMD128#061000 -r $2/CMD128#061000
echo "SYS/JIT";       atftp $1 --put -l rel/apple/JIT#FE1000 -r $2/SYS/JIT#FE1000
echo "SYS/JIT16";     atftp $1 --put -l rel/apple/JIT16#FE1000 -r $2/SYS/JIT16#FE1000
echo "SYS/JITUNE";    atftp $1 --put -l rel/apple/JITUNE#FE1000 -r $2/SYS/JITUNE#FE1000

# Core libraries
echo "SYS/ARGS";     atftp $1 --put -l rel/ARGS#FE1000 -r $2/SYS/ARGS#FE1000
echo "SYS/DHCP";     atftp $1 --put -l rel/DHCP#FE1000 -r $2/SYS/DHCP#FE1000
echo "SYS/ED";       atftp $1 --put -l rel/ED#FE1000 -r $2/SYS/ED#FE1000
echo "SYS/ETHERIP";  atftp $1 --put -l rel/ETHERIP#FE1000 -r $2/SYS/ETHERIP#FE1000
echo "SYS/MOUSE";    atftp $1 --put -l rel/apple/MOUSE#FE1000 -r $2/SYS/MOUSE#FE1000
echo "SYS/FIBER";    atftp $1 --put -l rel/FIBER#FE1000 -r $2/SYS/FIBER#FE1000
echo "SYS/FPSTR";    atftp $1 --put -l rel/FPSTR#FE1000 -r $2/SYS/FPSTR#FE1000
echo "SYS/FPU";      atftp $1 --put -l rel/FPU#FE1000 -r $2/SYS/FPU#FE1000
echo "SYS/INET";     atftp $1 --put -l rel/INET#FE1000 -r $2/SYS/INET#FE1000
echo "SYS/LONGJUMP"; atftp $1 --put -l rel/LONGJMP#FE1000 -r $2/SYS/LONGJMP#FE1000
echo "SYS/LZ4";      atftp $1 --put -l rel/LZ4#FE1000 -r $2/SYS/LZ4#FE1000
echo "SYS/MEMMGR";   atftp $1 --put -l rel/MEMMGR#FE1000 -r $2/SYS/MEMMGR#FE1000
echo "SYS/SANE";     atftp $1 --put -l rel/SANE#FE1000 -r $2/SYS/SANE#FE1000
echo "SYS/CONIO";    atftp $1 --put -l rel/apple/CONIO#FE1000 -r $2/SYS/CONIO#FE1000
echo "SYS/DGR";      atftp $1 --put -l rel/apple/DGR#FE1000 -r $2/SYS/DGR#FE1000
echo "SYS/FILEIO";   atftp $1 --put -l rel/apple/FILEIO#FE1000 -r $2/SYS/FILEIO#FE1000
echo "SYS/GRAFIX";   atftp $1 --put -l rel/apple/GRAFIX#FE1000 -r $2/SYS/GRAFIX#FE1000
echo "SYS/JOYBUZZ";  atftp $1 --put -l rel/apple/JOYBUZZ#FE1000 -r $2/SYS/JOYBUZZ#FE1000
echo "SYS/MON";      atftp $1 --put -l rel/apple/MON#FE1000 -r $2/SYS/MON#FE1000
echo "SYS/PORTIO";   atftp $1 --put -l rel/apple/PORTIO#FE1000 -r $2/SYS/PORTIO#FE1000
echo "SYS/SPIPORT";  atftp $1 --put -l rel/apple/SPIPORT#FE1000 -r $2/SYS/SPIPORT#FE1000
echo "SYS/UTHERNET2";atftp $1 --put -l rel/apple/UTHERNET2#FE1000 -r $2/SYS/UTHERNET2#FE1000
echo "SYS/UTHERNET"; atftp $1 --put -l rel/apple/UTHERNET#FE1000 -r $2/SYS/UTHERNET#FE1000

# Build tools
echo "BLD/PLASM";    atftp $1 --put -l rel/PLASM#FE1000 -r $2/BLD/PLASM#FE1000
echo "BLD/CODEOPT";  atftp $1 --put -l rel/CODEOPT#FE1000 -r $2/BLD/CODEOPT#FE1000

echo "INC/ARGS.PLH";     atftp $1 --option "mode netsacii" --put -l src/inc/args.plh -r $2/BLD/INC/ARGS.PLH#040000
echo "INC/CMDSYS.PLH";   atftp $1 --option "mode netsacii" --put -l src/inc/cmdsys.plh -r $2/BLD/INC/CMDSYS.PLH#040000
echo "INC/CONIO.PLH";    atftp $1 --option "mode netsacii" --put -l src/inc/conio.plh -r $2/BLD/INC/CONIO.PLH#040000
echo "INC/DGR.PLH";      atftp $1 --option "mode netsacii" --put -l src/inc/dgr.plh -r $2/BLD/INC/DGR.PLH#040000
echo "INC/FIBER.PLH";    atftp $1 --option "mode netsacii" --put -l src/inc/fiber.plh -r $2/BLD/INC/FIBER.PLH#040000
echo "INC/FILEIO.PLH";   atftp $1 --option "mode netsacii" --put -l src/inc/fileio.plh -r $2/BLD/INC/FILEIO.PLH#040000
echo "INC/FPSTR.PLH";    atftp $1 --option "mode netsacii" --put -l src/inc/fpstr.plh -r $2/BLD/INC/FPSTR.PLH#040000
echo "INC/FPU.PLH";      atftp $1 --option "mode netsacii" --put -l src/inc/fpu.plh -r $2/BLD/INC/FPU.PLH#040000
echo "INC/GRAFIX.PLH";   atftp $1 --option "mode netsacii" --put -l src/inc/grafix.plh -r $2/BLD/INC/GRAFIX.PLH#040000
echo "INC/INET.PLH";     atftp $1 --option "mode netsacii" --put -l src/inc/inet.plh -r $2/BLD/INC/INET.PLH#040000
echo "INC/JOYBUZZ.PLH";  atftp $1 --option "mode netsacii" --put -l src/inc/joybuzz.plh -r $2/BLD/INC/JOYBUZZ.PLH#040000
echo "INC/LONGJUMP.PLH"; atftp $1 --option "mode netsacii" --put -l src/inc/longjmp.plh -r $2/BLD/INC/LONGJUMP.PLH#040000
echo "INC/LZ4.PLH";      atftp $1 --option "mode netsacii" --put -l src/inc/lz4.plh -r $2/BLD/INC/LZ4.PLH#040000
echo "INC/MEMMGR.PLH";   atftp $1 --option "mode netsacii" --put -l src/inc/memmgr.plh -r $2/BLD/INC/MEMMGR.PLH#040000
echo "INC/MOUSE.PLH";    atftp $1 --option "mode netsacii" --put -l src/inc/mouse.plh -r $2/BLD/INC/MOUSE.PLH#040000
echo "INC/PORTIO.PLH";   atftp $1 --option "mode netsacii" --put -l src/inc/portio.plh -r $2/BLD/INC/PORTIO.PLH#040000
echo "INC/SANE.PLH";     atftp $1 --option "mode netsacii" --put -l src/inc/sane.plh -r $2/BLD/INC/SANE.PLH#040000
echo "INC/SDFAT.PLH";    atftp $1 --option "mode netsacii" --put -l src/inc/sdfat.plh -r $2/BLD/INC/SDFAT.PLH#040000
echo "INC/SNDSEQ.PLH";   atftp $1 --option "mode netsacii" --put -l src/inc/sndseq.plh -r $2/BLD/INC/SNDSEQ.PLH#040000
echo "INC/SPIPORT.PLH";  atftp $1 --option "mode netsacii" --put -l src/inc/spiport.plh -r $2/BLD/INC/SPIPORT.PLH#040000
echo "INC/TESTLIB.PLH";  atftp $1 --option "mode netsacii" --put -l src/inc/testlib.plh -r $2/BLD/INC/TESTLIB.PLH#040000
